### ISSUE TITLE
Ubuntu 8.04 - RedNotebook 0.8.9 won't start

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#109]
Hello!
I tried to start RedNotebook from the source directory like it is mentioned in the README file but the following error occurs:

igor$ ./rednotebook 
INFO     Writing log to file "/home/igor/.rednotebook/rednotebook.log"
INFO     Using libyaml for loading and dumping
INFO     AppDir: /opt/rednotebook-0.8.9/rednotebook
INFO     BaseDir: /opt/rednotebook-0.8.9
INFO     Adding BaseDir to sys.path
INFO     Writing log to file "/home/igor/.rednotebook/rednotebook.log"
INFO     Writing log to file "/home/igor/.rednotebook/rednotebook.log"
INFO     Using libyaml for loading and dumping
INFO     Using libyaml for loading and dumping
INFO     AppDir: /opt/rednotebook-0.8.9/rednotebook
INFO     AppDir: /opt/rednotebook-0.8.9/rednotebook
INFO     BaseDir: /opt/rednotebook-0.8.9
INFO     BaseDir: /opt/rednotebook-0.8.9
Traceback (most recent call last):
  File "./rednotebook", line 11, in <module>
    import rednotebook.redNotebook
  File "/opt/rednotebook-0.8.9/rednotebook/redNotebook.py", line 239, in <module>
    from rednotebook.gui.mainWindow import MainWindow
  File "/opt/rednotebook-0.8.9/rednotebook/gui/mainWindow.py", line 60, in <module>
    from rednotebook.gui.exportAssistant import ExportAssistant
  File "/opt/rednotebook-0.8.9/rednotebook/gui/exportAssistant.py", line 29, in <module>
    from rednotebook.gui import browser
  File "/opt/rednotebook-0.8.9/rednotebook/gui/browser.py", line 31, in <module>
    import glib
ImportError: No module named glib

and nothing happens.  I run Ubuntu 8.04 2.6.24-25-generic x86_64 with most recent updates.

Now, I am quite new to Linux so I'm not familiar with GTK or Python but I did try to look for the solution and in the browser.py I replaced:
import glib
with
import gobject (I found the similar problem on the net for some other app)
and then the RedNotebook started. After taking a quick look I turn it off.
Here is the output from CLI:

igor$ ./rednotebook 
INFO     Writing log to file "/home/igor/.rednotebook/rednotebook.log"
INFO     Using libyaml for loading and dumping
INFO     AppDir: /opt/rednotebook-0.8.9/rednotebook
INFO     BaseDir: /opt/rednotebook-0.8.9
INFO     Adding BaseDir to sys.path
Starting RedNotebook from the source directory
INFO     The config file /opt/rednotebook-0.8.9/rednotebook/files/default.cfg was read
INFO     The config file /home/igor/.rednotebook/configuration.cfg was read
INFO     Running in portable mode: 0
INFO     First Start: True
INFO     RedNotebook version: 0.8.9
INFO     System info: machine: x86_64, platform: Linux-2.6.24-25-generic-x86_64-with-debian-lenny-sid, processor: , python_version: 2.5.2, release: 2.6.24-25-generic, system: Linux, GTK version: (2, 12, 9), PyGTK version: (2, 12, 1), Yaml version: 3.06, 
/opt/rednotebook-0.8.9/rednotebook/gui/mainWindow.py:79: GtkWarning: Unknown property: GtkVBox.orientation

  self.builder.add_from_file(self.gladefile)
INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words']
INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
INFO     Opening journal at /home/igor/.rednotebook/data
INFO     The selected folder is empty. A new journal has been created.
INFO     Adding example content
INFO     Connected Signals: 1 2 3 6 15 20 
INFO     Trying to save the journal
INFO     The content has been saved to /home/igor/.rednotebook/data
INFO     Configuration has been saved to disk
INFO     Goodbye!

It looks like it's working ok but if u can check if anything is as You intended since You do have much more programing experience then me. 
I hope I didn't do anything wrong by changing that line of code and if I did, I'm sorry.

Igor Blazevic

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2009-11-17T12:49:30Z):

----------------------------------------

Hi, thanks for the excellent bug report. I applied your suggested fix and it seems to work.
Cheers!
