### ISSUE TITLE
exception on first run if ~/.rednotebook does not exist

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#17]
If the ~/.rednotebook directory does not already exist, RedNotebook raises an 
exception when trying to initialise logging:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 7, in <module>
    import rednotebook.redNotebook
  File "/usr/share/rednotebook/rednotebook/redNotebook.py", line 55, in <module>
    filemode='w',
  File "/usr/lib/python2.5/logging/__init__.py", line 1240, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.5/logging/__init__.py", line 770, in __init__
    stream = open(filename, mode)
IOError: [Errno 2] No such file or directory: '/home/jona/.rednotebook/rednotebook.log'

The attached patch checks at startup whether the directory exists, and creates
it if necessary just before loading the core redNotebook module.

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2009-06-25T18:10:23Z):

----------------------------------------

**Comment by jendrikseipp** [comment]
*Original comment by* **janitor** (2009-07-27T16:43:00Z):

----------------------------------------

This bug was fixed in the package rednotebook - 0.8.1-1

---------------
rednotebook (0.8.1-1) unstable; urgency=low

  * [995049] New upstream version

rednotebook (0.8.0-1) unstable; urgency=low

  * [79a906] New upstream version
  * [2a5e9b] Add Suggests for texlive-latex-extra to permit PDF output,
    and a hint in the binary package description

rednotebook (0.7.6-1) unstable; urgency=low

  * [b08360] New upstream release: add an Undo/Redo function (LP: #393277)
  * [be996f] Update debian/copyright

rednotebook (0.7.5-1) unstable; urgency=low

  [ Jonathan Wiltshire]
  * [960284] New upstream version

  [ Piotr Ożarowski ]
  * DM-Upload-Allowed set to yes

rednotebook (0.7.4-1) unstable; urgency=low

  * [309859] New upstream version:
    - create ~/.rednotebook before logging is initialized
      (Closes: #534608, LP: #392235)

 -- Jonathan Wiltshire <email address hidden>   Mon,  27 Jul 2009 16:27:11 +0100
