### ISSUE TITLE
rednotebook crashes when adding tags

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#18]
When im creating new tags rednotebook (fresh install) crashes very often. Apport analysis:

ProblemType: Crash
CrashCounter: 1
Date: Thu Jul 26 13:57:31 2012
ExecutablePath: /usr/share/rednotebook/run.py
ExecutableTimestamp: 1343122800
InterpreterPath: /usr/bin/python2.7
ProcCmdline: /usr/bin/python /usr/bin/rednotebook
ProcCwd: /home/###
ProcEnviron:
 PATH=(custom, no user)
 LANG=de_DE.UTF-8
 SHELL=/bin/bash
ProcMaps:
 ...
ProcStatus:
 Name:	rednotebook
 State:	R (running)
 Tgid:	8631
 Pid:	8631
 PPid:	1
 TracerPid:	0
 Uid:	1000	1000	1000	1000
 Gid:	1000	1000	1000	1000
 FDSize:	256
 Groups:	4 24 27 30 46 109 124 126 1000 
 VmPeak:	  204432 kB
 VmSize:	  204432 kB
 VmLck:	       0 kB
 VmPin:	       0 kB
 VmHWM:	   47724 kB
 VmRSS:	   47724 kB
 VmData:	   83476 kB
 VmStk:	     212 kB
 VmExe:	    2396 kB
 VmLib:	   78860 kB
 VmPTE:	     248 kB
 VmSwap:	       0 kB
 Threads:	7
 SigQ:	0/32124
 SigPnd:	0000000000000000
 ShdPnd:	0000000000000000
 SigBlk:	0000000000000000
 SigIgn:	0000000001001000
 SigCgt:	0000000180084027
 CapInh:	0000000000000000
 CapPrm:	0000000000000000
 CapEff:	0000000000000000
 CapBnd:	ffffffffffffffff
 Cpus_allowed:	3
 Cpus_allowed_list:	0-1
 Mems_allowed:	1
 Mems_allowed_list:	0
 voluntary_ctxt_switches:	7775
 nonvoluntary_ctxt_switches:	1949
PythonArgs: ['/usr/bin/rednotebook']
Traceback:
 Traceback (most recent call last):
   File "/usr/share/rednotebook/rednotebook/gui/search.py", line 44, in on_entry_changed
     self.search(self.get_active_text())
   File "/usr/share/rednotebook/rednotebook/gui/search.py", line 71, in search
     self.main_window.search_tree_view.update_data(search_text, tags)
   File "/usr/share/rednotebook/rednotebook/gui/search.py", line 93, in update_data
     for date_string, entries in self.journal.search(search_text, tags):
   File "/usr/share/rednotebook/rednotebook/journal.py", line 516, in search
     results.append(day.search(text, tags))
   File "/usr/share/rednotebook/rednotebook/data.py", line 186, in search
     entries = self.get_entries(day_tag)
   File "/usr/share/rednotebook/rednotebook/data.py", line 144, in get_entries
     return sorted(self.content.get(category, {}).keys())
 AttributeError: 'NoneType' object has no attribute 'keys'
UserGroups: adm cdrom davfs2 dip lpadmin plugdev sambashare sudo
ApportVersion: 2.0.1-0ubuntu11
Architecture: i386
Dependencies:
 aspell 0.60.7~20110707-1
 aspell-en 6.0-0-6ubuntu2
 coreutils 8.13-3ubuntu3
 dconf-gsettings-backend 0.12.0-0ubuntu1
 dconf-service 0.12.0-0ubuntu1
 debconf 1.5.42ubuntu1
 debianutils 4.2.1ubuntu2
 dictionaries-common 1.12.1ubuntu2
 dpkg 1.16.1.2ubuntu7
 fontconfig 2.8.0-3ubuntu9
 fontconfig-config 2.8.0-3ubuntu9
 gcc-4.6-base 4.6.3-1ubuntu5
 gir1.2-glib-2.0 1.32.0-1
 glib-networking 2.32.1-1ubuntu1
 glib-networking-common 2.32.1-1ubuntu1
 glib-networking-services 2.32.1-1ubuntu1
 gsettings-desktop-schemas 3.4.1-0ubuntu1
 iso-codes 3.31-1
 libacl1 2.2.51-5ubuntu1
 libaspell15 0.60.7~20110707-1
 libatk1.0-0 2.4.0-0ubuntu1
 libatk1.0-data 2.4.0-0ubuntu1
 libattr1 1:2.4.46-5ubuntu1
 libavahi-client3 0.6.30-5ubuntu2
 libavahi-common-data 0.6.30-5ubuntu2
 libavahi-common3 0.6.30-5ubuntu2
 libbz2-1.0 1.0.6-1
 libc-bin 2.15-0ubuntu10
 libc6 2.15-0ubuntu10
 libcairo2 1.10.2-6.1ubuntu3
 libcomerr2 1.42-1ubuntu2
 libcups2 1.5.3-0ubuntu1
 libdatrie1 0.2.5-3
 libdb5.1 5.1.25-11build1
 libdbus-1-3 1.4.18-1ubuntu1
 libdbus-glib-1-2 0.98-1ubuntu1
 libdconf0 0.12.0-0ubuntu1
 libenchant1c2a 1.6.0-7
 libexpat1 2.0.1-7.2ubuntu1
 libffi6 3.0.11~rc1-5
 libfontconfig1 2.8.0-3ubuntu9
 libfreetype6 2.4.8-1ubuntu2
 libgail18 2.24.10-0ubuntu6
 libgcc1 1:4.6.3-1ubuntu5
 libgcrypt11 1.5.0-3ubuntu0.1
 libgdk-pixbuf2.0-0 2.26.1-1
 libgdk-pixbuf2.0-common 2.26.1-1
 libgeoclue0 0.12.0-1ubuntu12
 libgirepository-1.0-1 1.32.0-1
 libglib2.0-0 2.32.3-0ubuntu1
 libgnutls26 2.12.14-5ubuntu3.1
 libgpg-error0 1.10-2ubuntu1
 libgssapi-krb5-2 1.10+dfsg~beta1-2ubuntu0.1
 libgstreamer-plugins-base0.10-0 0.10.36-1ubuntu0.1
 libgstreamer0.10-0 0.10.36-1ubuntu1
 libgtk2.0-0 2.24.10-0ubuntu6
 libgtk2.0-common 2.24.10-0ubuntu6
 libhunspell-1.3-0 1.3.2-4
 libice6 2:1.0.7-2build1
 libicu48 4.8.1.1-3
 libjasper1 1.900.1-13
 libjavascriptcoregtk-1.0-0 1.8.0-0ubuntu2
 libjpeg-turbo8 1.1.90+svn733-0ubuntu4.1
 libjpeg8 8c-2ubuntu7
 libk5crypto3 1.10+dfsg~beta1-2ubuntu0.1
 libkeyutils1 1.5.2-2
 libkrb5-3 1.10+dfsg~beta1-2ubuntu0.1
 libkrb5support0 1.10+dfsg~beta1-2ubuntu0.1
 liblzma5 5.1.1alpha+20110809-3
 libncursesw5 5.9-4
 liborc-0.4-0 1:0.4.16-1ubuntu2
 libp11-kit0 0.12-2ubuntu1
 libpam-modules 1.1.3-7ubuntu2
 libpam-modules-bin 1.1.3-7ubuntu2
 libpam0g 1.1.3-7ubuntu2
 libpango1.0-0 1.30.0-0ubuntu3.1
 libpcre3 8.12-4
 libpixman-1-0 0.24.4-1
 libpng12-0 1.2.46-3ubuntu4
 libproxy1 0.4.7-0ubuntu4
 libreadline6 6.2-8
 libselinux1 2.1.0-4.1ubuntu1
 libsm6 2:1.2.0-2build1
 libsoup2.4-1 2.38.1-1
 libsqlite3-0 3.7.9-2ubuntu1
 libssl1.0.0 1.0.1-4ubuntu5.3
 libstdc++6 4.6.3-1ubuntu5
 libtasn1-3 2.10-1ubuntu1.1
 libtext-iconv-perl 1.7-5
 libthai-data 0.1.16-3
 libthai0 0.1.16-3
 libtiff4 3.9.5-2ubuntu1.2
 libtinfo5 5.9-4
 libuuid1 2.20.1-1ubuntu3
 libwebkitgtk-1.0-0 1.8.0-0ubuntu2
 libwebkitgtk-1.0-common 1.8.0-0ubuntu2
 libx11-6 2:1.4.99.1-0ubuntu2
 libx11-data 2:1.4.99.1-0ubuntu2
 libxau6 1:1.0.6-4
 libxcb-render0 1.8.1-1
 libxcb-shm0 1.8.1-1
 libxcb1 1.8.1-1
 libxcomposite1 1:0.4.3-2build1
 libxcursor1 1:1.1.12-1
 libxdamage1 1:1.1.3-2build1
 libxdmcp6 1:1.1.0-4
 libxext6 2:1.3.0-3build1
 libxfixes3 1:5.0-4ubuntu4
 libxft2 2.2.0-3ubuntu2
 libxi6 2:1.6.0-0ubuntu2
 libxinerama1 2:1.1.1-3build1
 libxml2 2.7.8.dfsg-5.1ubuntu4.1
 libxrandr2 2:1.3.2-2
 libxrender1 1:0.9.6-2build1
 libxslt1.1 1.1.26-8ubuntu1
 libxt6 1:1.1.1-2build1
 libyaml-0-2 0.1.4-2
 lsb-base 4.0-0ubuntu20
 mime-support 3.51-1ubuntu1
 multiarch-support 2.15-0ubuntu10
 ncurses-bin 5.9-4
 passwd 1:4.1.4.2+svn3283-3ubuntu5
 perl-base 5.14.2-6ubuntu2
 python 2.7.3-0ubuntu2
 python-cairo 1.8.8-1ubuntu3
 python-gi 3.2.2-1~precise
 python-gobject 3.2.2-1~precise
 python-gobject-2 2.28.6-10ubuntu1
 python-gtk2 2.24.0-3
 python-minimal 2.7.3-0ubuntu2
 python-support 1.0.14ubuntu2
 python-webkit 1.1.8-2ubuntu2
 python-yaml 3.10-2
 python2.7 2.7.3-0ubuntu3
 python2.7-minimal 2.7.3-0ubuntu3
 readline-common 6.2-8
 sed 4.2.1-9
 sensible-utils 0.0.6ubuntu2
 shared-mime-info 1.0-0ubuntu4.1
 tar 1.26-4ubuntu1
 ttf-dejavu-core 2.33-2ubuntu1
 tzdata 2012b-1
 ucf 3.0025+nmu2ubuntu1
 x11-common 1:7.6+12ubuntu1
 xz-utils 5.1.1alpha+20110809-3
 zlib1g 1:1.2.3.4.dfsg-3ubuntu4
DistroRelease: Ubuntu 12.04
InstallationMedia: Ubuntu 12.04 LTS "Precise Pangolin" - Release i386 (20120423)
Package: rednotebook 1.5.0-1~1027~precise1 [origin: LP-PPA-rednotebook-daily]
PackageArchitecture: all
ProcVersionSignature: Ubuntu 3.2.0-27.43-generic-pae 3.2.21
SourcePackage: rednotebook
Tags: third-party-packages precise
Title: run.py crashed with AttributeError in get_entries(): 'NoneType' object has no attribute 'keys'
Uname: Linux 3.2.0-27-generic-pae i686
UnreportableReason: Dies ist kein offizielles Ubuntu-Paket. Bitte entfernen Sie alle Pakete von Drittanbietern und wiederholen Sie den Vorgang.
UpgradeStatus: No upgrade log present (probably fresh install)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-07-26T13:31:58Z):

----------------------------------------

Thanks for reporting this. Can you wait until revision 1028 is installed 
from the PPA (currently you have 1027) and tell me if the error is fixed 
there, please? The version should appear there in the next 1-2 days.

**Comment by jendrikseipp** [comment]
*Original comment by* **margarethe-meier** (2012-07-28T08:05:53Z):

----------------------------------------

Hi,

today i've upgraded to 1028 and it seems the error doesn't occur any more. But i encountered another error when searching in categories:

ProblemType: Crash
CrashCounter: 1
Date: Sat Jul 28 09:59:20 2012
ExecutablePath: /usr/share/rednotebook/run.py
ExecutableTimestamp: 1343311878
InterpreterPath: /usr/bin/python2.7
ProcCmdline: /usr/bin/python /usr/bin/rednotebook
ProcCwd: /home/mahadi
ProcEnviron:
 PATH=(custom, no user)
 LANG=de_DE.UTF-8
 SHELL=/bin/bash
ProcMaps: [...]
ProcStatus: [...]
PythonArgs: ['/usr/bin/rednotebook']
Traceback:
 Traceback (most recent call last):
   File "/usr/share/rednotebook/rednotebook/gui/search.py", line 44, in on_entry_changed
     self.search(self.get_active_text())
   File "/usr/share/rednotebook/rednotebook/gui/search.py", line 71, in search
     self.main_window.search_tree_view.update_data(search_text, tags)
   File "/usr/share/rednotebook/rednotebook/gui/search.py", line 93, in update_data
     for date_string, entries in self.journal.search(search_text, tags):
   File "/usr/share/rednotebook/rednotebook/journal.py", line 516, in search
     results.append(day.search(text, tags))
   File "/usr/share/rednotebook/rednotebook/data.py", line 183, in search
     for day_tag, entries in self.get_category_content_pairs():
 ValueError: too many values to unpack
UserGroups: adm cdrom davfs2 dip lpadmin plugdev sambashare sudo
ApportVersion: 2.0.1-0ubuntu11
Architecture: i386
Dependencies: [...]
DistroRelease: Ubuntu 12.04
InstallationMedia: Ubuntu 12.04 LTS "Precise Pangolin" - Release i386 (20120423)
Package: rednotebook 1.5.0-1~1028~precise1 [origin: LP-PPA-rednotebook-daily]
PackageArchitecture: all
ProcVersionSignature: Ubuntu 3.2.0-27.43-generic-pae 3.2.21
SourcePackage: rednotebook
Tags: third-party-packages precise running-unity
Title: run.py crashed with ValueError in search(): too many values to unpack
Uname: Linux 3.2.0-27-generic-pae i686
UnreportableReason: Dies ist kein offizielles Ubuntu-Paket. Bitte entfernen Sie alle Pakete von Drittanbietern und wiederholen Sie den Vorgang.
UpgradeStatus: No upgrade log present (probably fresh install)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-07-28T09:54:11Z):

----------------------------------------

Thanks for report! This is fixed in r1029.
