### ISSUE TITLE
run.py crashed with GError in enable_spell_check()

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#197]
Binary package hint: rednotebook

rednotebook 
INFO     Using libyaml for loading and dumping
INFO     AppDir: /usr/share/rednotebook/rednotebook
INFO     BaseDir: /usr/share/rednotebook
INFO     First Start: True
INFO     RedNotebook version: 0.8.1
INFO     System info: machine: x86_64, platform: Linux-2.6.31-12-generic-x86_64-with-Ubuntu-9.10-karmic, processor: , python_version: 2.6.3, release: 2.6.31-12-generic, system: Linux, GTK version: (2, 18, 2), PyGTK version: (2, 16, 0), Yaml version: 3.09, 
INFO     The config file /usr/share/rednotebook/rednotebook/files/default.cfg was read
INFO     The config file /home/arpu/.rednotebook/configuration.cfg was read
/usr/share/rednotebook/rednotebook/gui/mainWindow.py:66: GtkWarning: gtk_toolbar_set_icon_size: assertion `icon_size != GTK_ICON_SIZE_INVALID' failed
  self.wTree = gtk.glade.XML(self.gladefile)
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.redNotebook.main()
  File "/usr/share/rednotebook/rednotebook/redNotebook.py", line 777, in main
    redNotebook = RedNotebook()
  File "/usr/share/rednotebook/rednotebook/redNotebook.py", line 177, in __init__
    self.frame = MainWindow(self)
  File "/usr/share/rednotebook/rednotebook/gui/mainWindow.py", line 97, in __init__
    self.html_editor = HtmlEditor()
  File "/usr/share/rednotebook/rednotebook/gui/richtext.py", line 278, in __init__
    self._textview = HtmlView()	# textview
  File "/usr/share/rednotebook/rednotebook/gui/richtext.py", line 141, in __init__
    RichTextView.__init__(self)
  File "/usr/share/rednotebook/rednotebook/gui/keepnote/gui/richtext/__init__.py", line 294, in __init__
    self.enable_spell_check(True)
  File "/usr/share/rednotebook/rednotebook/gui/keepnote/gui/richtext/__init__.py", line 1204, in enable_spell_check
    self._spell_checker = gtkspell.Spell(self)
glib.GError: enchant error for language: de_AT.UTF-8

ProblemType: Crash
Architecture: amd64
Date: Fri Oct  9 04:27:30 2009
DistroRelease: Ubuntu 9.10
ExecutablePath: /usr/share/rednotebook/run.py
InterpreterPath: /usr/bin/python2.6
Package: rednotebook 0.8.1-1
PackageArchitecture: all
ProcCmdline: /usr/bin/python /usr/bin/rednotebook
ProcEnviron:
 LANGUAGE=de_AT.UTF-8
 LANG=de_AT.UTF-8
 SHELL=/bin/bash
ProcVersionSignature: Ubuntu 2.6.31-12.41-generic
PythonArgs: ['/usr/bin/rednotebook']
SourcePackage: rednotebook
Title: run.py crashed with GError in enable_spell_check()
Uname: Linux 2.6.31-12-generic x86_64
UserGroups: adm admin cdrom dialout fuse lpadmin plugdev sambashare

**Comment by jendrikseipp** [comment]
*Original comment by* **whitewindow** (2009-10-09T02:31:35Z):

----------------------------------------

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-09T22:31:49Z):

----------------------------------------

Hi,

This is quite an old version of RedNotebook and I can't reproduce the error. Please try and do the same and if you cannot either, I will close the bug.

Thanks

**Comment by jendrikseipp** [comment]
*Original comment by* **janitor** (2010-12-10T04:19:17Z):

----------------------------------------

[Expired for rednotebook (Ubuntu) because there has been no activity for 60 days.]
