### ISSUE TITLE
Latest update causes crash on startup

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#20]
After updating to version 1.6.5, I am receiving this error on startup:

The procedure entry point _except_handler4_common could not be located in the dynamic link library msvcrt.dll.

I've tried to roll back to the previous version, but the error persists...

Here is the rednotebook.exe.log:

Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 78, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 78, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 78, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 77, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 77, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 78, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-28T11:23:53Z):

----------------------------------------

Thanks for the report! Could you please try uninstalling RedNotebook 
completely and try installing version 1.6.5 again? What error message do 
you get then?

**Comment by jendrikseipp** [comment]
*Original comment by* **junkmailcentral2008** (2012-12-28T18:26:41Z):

----------------------------------------

On 12/28/2012 6:23 AM, Jendrik Seipp wrote:
> Thanks for the report! Could you please try uninstalling RedNotebook
> completely and try installing version 1.6.5 again? What error message do
> you get then?
>
I tried to uninstall, but got the same error message as when trying to 
run the program.

Then I get this message:

This installation can only be uninstalled from 64-bit Windows.

I then used Revo Uninstaller to completely uninstall it, and made sure 
there were no leftover files/folders or Registry entries.

Reinstalled version 1.6.5 and got the same error message again...

Here's the log file:

> Traceback (most recent call last):
>   File "rednotebook", line 11, in <module>
>   File "rednotebook\journal.pyc", line 78, in <module>
>   File "rednotebook\util\utils.pyc", line 30, in <module>
>   File "gtk\__init__.pyc", line 40, in <module>
>   File "gtk\_gtk.pyc", line 12, in <module>
>   File "gtk\_gtk.pyc", line 10, in __load
> ImportError: DLL load failed: The specified procedure could not be found.

Help!  I miss my RedNotebook! :(

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-28T22:45:45Z):

----------------------------------------

Which windows version do you use? 32 or 64 bit? Can you try version 1.6.5 on any other windows systems?

**Comment by jendrikseipp** [comment]
*Original comment by* **joesepie** (2012-12-29T07:45:48Z):

----------------------------------------

I'm experiencing the same problem after upgrading to the latest version 1.6.5. OS: Windows Vista - 32 bit SP 2

rednotebook.exe.log:
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 78, in <module>
  File "rednotebook\util\utils.pyc", line 30, in <module>
  File "gtk\__init__.pyc", line 40, in <module>
  File "gtk\_gtk.pyc", line 12, in <module>
  File "gtk\_gtk.pyc", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found.

Has this version been tested before releasing for all to download and use?

**Comment by jendrikseipp** [comment]
*Original comment by* **joesepie** (2012-12-29T08:16:30Z):

----------------------------------------

Rolled back to previous version 1.6.1 - working without the above reported issue.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-29T11:18:09Z):

----------------------------------------

Am 29.12.2012 08:45, schrieb Joe Sepie:
> Has this version been tested before releasing for all to download and
> use?
Yes, the beta had been confirmed to work on at least 5 windows setups.

**Comment by jendrikseipp** [comment]
*Original comment by* **joesepie** (2012-12-29T13:35:23Z):

----------------------------------------

Any idea what may be causing this issue?

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-01-10T22:37:46Z):

----------------------------------------

I have tried a new method for compiling the RedNotebook executable on Windows. Could someone who experienced the error previously check if one or both of the linked archives below work for them, please?

https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta5.zip (Unpack and run journal.exe)
https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta7.zip (Unpack and run rednotebook.exe)

**Comment by jendrikseipp** [comment]
*Original comment by* **junkmailcentral2008** (2013-01-11T18:18:29Z):

----------------------------------------

On 1/10/2013 5:37 PM, Jendrik Seipp wrote:
> I have tried a new method for compiling the RedNotebook executable on
> Windows. Could someone who experienced the error previously check if one
> or both of the linked archives below work for them, please?
>
> https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta5.zip (Unpack and run journal.exe)
> https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta7.zip (Unpack and run rednotebook.exe)
>
Both versions run okay on my Windows XP with Service Pack 3 system :)

Beta 5 displays a DOS window when run, showing all activities.

Now if you can just get the Installer to work, we'll be in business! :P

Thank You so much for your continued support, and for the great 
RedNotebook :)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-01-16T10:55:35Z):

----------------------------------------

Here you go ;)

https://dl.dropbox.com/u/4780737/rednotebook-1.6.6-beta1.exe

**Comment by jendrikseipp** [comment]
*Original comment by* **junkmailcentral2008** (2013-01-16T21:09:09Z):

----------------------------------------

On 1/16/2013 5:55 AM, Jendrik Seipp wrote:
> Here you go ;)
>
> https://dl.dropbox.com/u/4780737/rednotebook-1.6.6-beta1.exe
>
Yay!

It works flawlessly :)

Thank You so much, kind Sir :)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-01-21T17:35:18Z):

----------------------------------------

This has been fixed in 1.6.6.
