### ISSUE TITLE
Export of old log books fail on Windows XP

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#216]
After installing version 1.1.1 of Rednotbook I now see that it export very nicely on Windows if I create a new log book. However, it does not want to export my old log book. When I try I get the following in the log:

2010-10-21 11:50:04,358 DEBUG    Selected Categories for Export: [u'Tags']
Traceback (most recent call last):
  File "rednotebook\gui\exports.pyc", line 356, in _on_close
  File "rednotebook\gui\exports.pyc", line 434, in export
  File "rednotebook\gui\exports.pyc", line 451, in export_pdf
  File "rednotebook\gui\exports.pyc", line 418, in get_export_string
  File "rednotebook\util\markup.pyc", line 91, in get_markup_for_day
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 3-7: unsupported Unicode code range
2010-10-21 11:50:42,030 INFO     Exporting to PDF
2010-10-21 11:50:42,046 DEBUG    Selected Categories for Export: [u'Tags']
Traceback (most recent call last):
  File "rednotebook\gui\exports.pyc", line 356, in _on_close
  File "rednotebook\gui\exports.pyc", line 434, in export
  File "rednotebook\gui\exports.pyc", line 451, in export_pdf
  File "rednotebook\gui\exports.pyc", line 418, in get_export_string
  File "rednotebook\util\markup.pyc", line 91, in get_markup_for_day
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 3-7: unsupported Unicode code range

I error message there is similar to the one in this bug report: https://bugs.launchpad.net/rednotebook/+bug/575999 so I suspect it is related to the same issue.

I know that this is sort of a pseudo issue, since the export issue really has been fixed. But I have a lot of information in my old logs that I want to be able to export.

Anyway, if I read the errors correctly this is somehow related to non utf8 characters. Am I correct in assuming that this issue may be related to having such characters already present in the old log files (and the fix to the old export issue was related to not writing such characters to the log books in the first place). And if so, maybe it could fixed by replacing these affending characters in a texteditor or with a python script?

Regards Kenneth

**Comment by jendrikseipp** [comment]
*Original comment by* **k-nielsen81** (2010-10-21T10:16:41Z):

----------------------------------------

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-11-26T18:21:12Z):

----------------------------------------

Do you still get the error with the newest beta?

http://dl.dropbox.com/u/4780737/rednotebook-1.1.2-b1-win32.exe

**Comment by jendrikseipp** [comment]
*Original comment by* **k-nielsen81** (2010-12-14T15:52:56Z):

----------------------------------------

Hallo Jendrik

Sorry for taking so long to get back to you. I have now tested it. Exporting the logbook does not produce an error in the log with the new version HOWEVER, the export still does not work. It now makes a .pdf file but it is invalid and cannot be opened.

Could you please advice me, which kind of information do you need to debug this.

Regards Kenneth

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-12-14T17:17:47Z):

----------------------------------------

You could export the same days to html, look at the file and search for possible error sources. The PDF is just a rendering of the HTML file.

**Comment by jendrikseipp** [comment]
*Original comment by* **janitor** (2011-04-21T04:22:40Z):

----------------------------------------

[Expired for RedNotebook because there has been no activity for 60 days.]

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-05-03T14:24:02Z):

----------------------------------------

Is this still happening in 1.1.4?

**Comment by jendrikseipp** [comment]
*Original comment by* **k-nielsen81** (2011-05-05T11:33:29Z):

----------------------------------------

No IT WORKS. Thank you, thank you, thank you. There however seem to be a minor character set problem with the exports, but I'll do a separate bug report on that.

Seriously, thanks for fixing this.
