### ISSUE TITLE
Crash when launched and error loading file

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#251]
Hello,

I've been running Rednotebook on Ubuntu 12.04 for a few months. Today I tried to open it but it failed. A window popped up for about a second, didn't show anything inside it, then immediately closed. I've tried a few things: I upgraded from my old version (which was I think 1.1.8) to the current version; then removed it entirely, restarted, then reinstalled. None of this has worked. 

Here's the logfile:

2013-03-19 11:58:48,922 DEBUG    Debug message
2013-03-19 11:58:48,922 INFO     Writing log to file "/home/typer/.rednotebook/rednotebook.log"
2013-03-19 11:58:48,922 INFO     System encoding: UTF-8
2013-03-19 11:58:48,922 INFO     Language code: en_US
2013-03-19 11:58:48,929 INFO     MathJax location: http://cdn.mathjax.org/mathjax/latest/MathJax.js
2013-03-19 11:58:49,010 INFO     Running in portable mode: False
2013-03-19 11:58:49,011 INFO     First Start: False
2013-03-19 11:58:49,011 INFO     RedNotebook version: 1.7.1
2013-03-19 11:58:49,014 INFO     System info: machine: i686, platform: Linux-3.2.0-39-generic-pae-i686-with-Ubuntu-12.04-precise, processor: i686, python_version: 2.7.3, release: 3.2.0-39-generic-pae, system: Linux, GTK version: (2, 24, 10), PyGTK version: (2, 24, 0), Yaml version: 3.10
2013-03-19 11:58:49,275 DEBUG    Default font: Ubuntu 11
2013-03-19 11:58:49,276 DEBUG    Default size: 11
2013-03-19 11:58:49,351 INFO     Cloud ignore list: [u'comma', u'filter', u'separated', u'these', u'words']
2013-03-19 11:58:49,351 INFO     Cloud include list: [u'job', u'mtv', u'play', u'spam', u'work']
2013-03-19 11:58:49,352 DEBUG    Start compiling regexes
2013-03-19 11:58:49,352 DEBUG    Finished
2013-03-19 11:58:49,376 DEBUG    Tray icon visible: False
2013-03-19 11:58:49,378 INFO     Opening journal at u'/home/typer/Documents/notebook'
2013-03-19 11:58:49,378 DEBUG    Starting to load files in dir "/home/typer/Documents/notebook"
2013-03-19 11:58:49,379 DEBUG    Loading file "/home/typer/Documents/notebook/2010-11.txt"
2013-03-19 11:58:49,379 DEBUG    Loading file "/home/typer/Documents/notebook/2010-12.txt"
2013-03-19 11:58:49,380 DEBUG    Loading file "/home/typer/Documents/notebook/2011-01.txt"
2013-03-19 11:58:49,380 DEBUG    Loading file "/home/typer/Documents/notebook/2011-02.txt"
2013-03-19 11:58:49,381 DEBUG    Loading file "/home/typer/Documents/notebook/2011-03.txt"
2013-03-19 11:58:49,381 DEBUG    Loading file "/home/typer/Documents/notebook/2011-04.txt"
2013-03-19 11:58:49,381 DEBUG    Loading file "/home/typer/Documents/notebook/2011-05.txt"
2013-03-19 11:58:49,382 DEBUG    Loading file "/home/typer/Documents/notebook/2011-06.txt"
2013-03-19 11:58:49,382 DEBUG    Loading file "/home/typer/Documents/notebook/2011-07.txt"
2013-03-19 11:58:49,383 DEBUG    Loading file "/home/typer/Documents/notebook/2011-08.txt"
2013-03-19 11:58:49,383 DEBUG    Loading file "/home/typer/Documents/notebook/2011-09.txt"
2013-03-19 11:58:49,383 DEBUG    Loading file "/home/typer/Documents/notebook/2011-10.txt"
2013-03-19 11:58:49,384 DEBUG    Loading file "/home/typer/Documents/notebook/2011-11.txt"
2013-03-19 11:58:49,384 DEBUG    Loading file "/home/typer/Documents/notebook/2011-12.txt"
2013-03-19 11:58:49,384 DEBUG    Loading file "/home/typer/Documents/notebook/2012-01.txt"
2013-03-19 11:58:49,385 DEBUG    Loading file "/home/typer/Documents/notebook/2012-02.txt"
2013-03-19 11:58:49,385 DEBUG    Loading file "/home/typer/Documents/notebook/2012-03.txt"
2013-03-19 11:58:49,386 DEBUG    Loading file "/home/typer/Documents/notebook/2012-04.txt"
2013-03-19 11:58:49,394 DEBUG    Loading file "/home/typer/Documents/notebook/2012-05.txt"
2013-03-19 11:58:49,403 DEBUG    Loading file "/home/typer/Documents/notebook/2012-06.txt"
2013-03-19 11:58:49,409 DEBUG    Loading file "/home/typer/Documents/notebook/2012-07.txt"
2013-03-19 11:58:49,412 DEBUG    Loading file "/home/typer/Documents/notebook/2012-08.txt"
2013-03-19 11:58:49,417 DEBUG    Loading file "/home/typer/Documents/notebook/2012-09.txt"
2013-03-19 11:58:49,421 DEBUG    Loading file "/home/typer/Documents/notebook/2012-10.txt"
2013-03-19 11:58:49,427 DEBUG    Loading file "/home/typer/Documents/notebook/2012-11.txt"
2013-03-19 11:58:49,430 DEBUG    Loading file "/home/typer/Documents/notebook/2012-12.txt"
2013-03-19 11:58:49,434 DEBUG    Loading file "/home/typer/Documents/notebook/2013-01.txt"
2013-03-19 11:58:49,435 DEBUG    Loading file "/home/typer/Documents/notebook/2013-02.txt"
2013-03-19 11:58:49,437 DEBUG    Loading file "/home/typer/Documents/notebook/2013-03.txt"
2013-03-19 11:58:49,437 ERROR    An error occured while reading /home/typer/Documents/notebook/2013-03.txt:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.journal.main()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 560, in main
    journal = Journal()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 217, in __init__
    self.open_journal(journal_path)
  File "/usr/share/rednotebook/rednotebook/journal.py", line 326, in open_journal
    self.months = storage.load_all_months_from_disk(data_dir)
  File "/usr/share/rednotebook/rednotebook/storage.py", line 96, in load_all_months_from_disk
    month = _load_month_from_disk(path, year_number, month_number)
  File "/usr/share/rednotebook/rednotebook/storage.py", line 72, in _load_month_from_disk
    month_contents = yaml.load(month_file, Loader=Loader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 702, in _yaml.CParser.get_single_node (ext/_yaml.c:7647)
  File "_yaml.pyx", line 903, in _yaml.CParser._parse_next_event (ext/_yaml.c:10371)
  File "_yaml.pyx", line 912, in _yaml.input_handler (ext/_yaml.c:10483)
  File "/usr/lib/python2.7/codecs.py", line 671, in read
    return self.reader.read(size)
  File "/usr/lib/python2.7/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x98 in position 2: invalid start byte

I checked the file (2013-03-19) that says error, and it's gibberish.

Not sure this is related - but last night or the night before there was a mysterious question mark application in the sidebar. I thought it was related to another program, but it might have been related to Rednotebook.

Thanks

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-03-19T17:43:29Z):

----------------------------------------


Am 19.03.2013 17:07, schrieb John Applebaum:
> UnicodeDecodeError: 'utf8' codec can't decode byte 0x98 in position 2: invalid start byte
>
> I checked the file (2013-03-19) that says error, and it's gibberish.
RedNotebook has probably crashed during the last save operation.
The easiest solution is to move the file 2013-03.txt somewhere else and 
manually reinsert your text into RedNotebook.
>
> Not sure this is related - but last night or the night before there was
> a mysterious question mark application in the sidebar. I thought it was
> related to another program, but it might have been related to
> Rednotebook.
Do you mean an exclamation mark with red background? This is the dialog 
that pops up when an application crashed. In those cases, you should 
click on the exclamation mark and report the error.

**Comment by jendrikseipp** [comment]
*Original comment by* **johna514** (2013-03-19T17:55:45Z):

----------------------------------------

Hi, Thanks for the response.

Removing the file from the folder solved the problem. However, the file is still gibberish. Any way to salvage that information?

No, it was a question mark. I guess it was unrelated.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-03-19T18:15:28Z):

----------------------------------------

Not that I know of, sorry.

Am 19.03.2013 18:55, schrieb John Applebaum:
> Any way to salvage that information?
