### ISSUE TITLE
./run Doesn't Work

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#311]
When I try to use the "./run" command in the README.md to run locally (to work on my repsin of RN), I get this error:

svetlana@svetlana-desktop:~/Dropbox/ELNrednotebook$ ./run
Traceback (most recent call last):
  File "rednotebook/journal.py", line 126, in <module>
    setup_logging(dirs.log_file)
  File "rednotebook/journal.py", line 88, in setup_logging
    file_logging_stream = open(log_file, 'w')
IOError: [Errno 13] Permission denied: u'/home/svetlana/.rednotebook/rednotebook.log'

But oddly enough, when I use sudo with the command it runs.  This is why I brought up that PR on Github.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2016-05-11T16:03:10Z):

----------------------------------------

It seems you don't have write permissions in your home folder or the 
.rednotebook folder. You'll probably have to use chown or chmod to fix this.

**Comment by jendrikseipp** [comment]
*Original comment by* **belkinsa** (2016-05-11T16:22:00Z):

----------------------------------------

I tried to change the permissions on the .rednotbook folder (home folder is fine) but it's still says that root is the owner, group, and user.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2016-05-11T16:57:01Z):

----------------------------------------

chown should change this.

**Comment by jendrikseipp** [comment]
*Original comment by* **belkinsa** (2016-05-15T15:13:42Z):

----------------------------------------

chown worked.  Thanks.
