### ISSUE TITLE
Request for autostart is ignored;  using Linux Mint 18

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#317]
*Originally reported by* **exedukator** at https://bugs.launchpad.net/bugs/1628497 (2016-09-28T12:35:37Z):

------------------------------------

file:///home/cnb/.rednotebook/rednotebook.log

When "Load Rednotebook at startup" is clicked, then OK, the Preferences window does not close, and - if closed manually by clicking top-right - the Load at startup checkbox does not retain the check.  Rednotebook does not restart on next computer switch-on.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2016-09-28T13:42:00Z):

----------------------------------------

Could you please paste the log here?

**Comment by jendrikseipp** [comment]
*Original comment by* **jerry89** (2016-10-05T20:45:54Z):

----------------------------------------

I have the same problem.
Here is what I get on the terminal.

When I try to close the preferences window with OK:

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/gui/menu.py", line 263, in on_options_menuitem_activate
    self.main_window.options_manager.on_options_dialog()
  File "/usr/share/rednotebook/rednotebook/gui/options.py", line 320, in on_options_dialog
    self.save_options()
  File "/usr/share/rednotebook/rednotebook/gui/options.py", line 354, in save_options
    option.set()
  File "/usr/share/rednotebook/rednotebook/gui/options.py", line 99, in set
    filesystem.make_file_with_dir(self.autostart_file, info.desktop_file)
  File "/usr/share/rednotebook/rednotebook/util/filesystem.py", line 210, in make_file_with_dir
    make_file(file, content)
  File "/usr/share/rednotebook/rednotebook/util/filesystem.py", line 199, in make_file
    write_file(file, content)
  File "/usr/share/rednotebook/rednotebook/util/filesystem.py", line 179, in write_file
    assert os.path.isabs(filename)
AssertionError

And later:

2016-10-05 22:16:20,127 DEBUG    Add mathjax code: False
2016-10-05 22:16:21,371 DEBUG    Add mathjax code: False
2016-10-05 22:16:21,954 DEBUG    Add mathjax code: False
2016-10-05 22:16:22,780 DEBUG    Add mathjax code: False
2016-10-05 22:16:38,823 DEBUG    Add mathjax code: False
2016-10-05 22:25:25,551 INFO     Wrote file /home/***
2016-10-05 22:25:25,551 INFO     The content has been saved to /home/***
2016-10-05 22:25:25,552 INFO     The content has been saved to u'/home/***'
2016-10-05 22:25:25,553 DEBUG    Update the cloud
2016-10-05 22:25:25,568 DEBUG    Cloud updated
2016-10-05 22:35:25,629 INFO     Nothing to save
2016-10-05 22:40:14,181 DEBUG    Running on Linux. Is installed. Adding autostart option
2016-10-05 22:40:27,319 DEBUG    Running on Linux. Is installed. Adding autostart option

**Comment by jendrikseipp** [comment]
*Original comment by* **jerry89** (2016-10-05T21:08:57Z):

----------------------------------------

I forget to mention that I'm also using linux mint (but the previous one, 17.3) and RedNotebook 1.14 (daily builds)

**Comment by jendrikseipp** [comment]
*Original comment by* **iamjackg** (2016-12-02T16:19:17Z):

----------------------------------------

I found the bug and opened a pull request to solve it.

https://github.com/jendrikseipp/rednotebook/pull/13

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2016-12-02T17:58:14Z):

----------------------------------------

Thanks for the fix!

**Comment by jendrikseipp** [comment]
*Original comment by* **iamjackg** (2016-12-02T18:04:28Z):

----------------------------------------

No problem!
