### ISSUE TITLE
Starting 2.0 fails

### ISSUE THREAD

**Issue by SanskritFritz** [jendrikseipp/rednotebook#326]
I installed Rednotebook 2.0 this way:
```
python setup.py build
python setup.py install --root="${pkgdir}" --prefix=/usr
```

Starting Rednotebook gives this:
```
Adding /usr/lib/python3.6/site-packages to sys.path
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 11, in <module>
    import rednotebook.journal
  File "/usr/lib/python3.6/site-packages/rednotebook/journal.py", line 87, in <module>
    from rednotebook.util import markup
  File "/usr/lib/python3.6/site-packages/rednotebook/util/markup.py", line 44, in <module>
    REGEX_NAMED_LINK = re.compile(r'(\[)(.*?)(\s"")(\S.*?\S)(""\])', flags=re.I | re.L)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/lib/python3.6/sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

What am I doing wrong?

**Comment by jendrikseipp** [comment]
You'll need to use Python 3.

**Comment by SanskritFritz** [comment]
For the best I know I am using python 3. The error message also shows "/usr/lib/python3.6". I'm using Archlinux, where env python points to python 3.

**Comment by jendrikseipp** [comment]
Sorry, I misinterpreted the error message. The first exception is expected, it just tried to run RedNotebook from the git repo, but since the app is installed, this fails and tries to run the installed RedNotebook version. This fails due to Python 3.6 dropping support for using re.LOCALE for unicode strings. I fixed this now. Does RedNotebook work corrrectly now? There might be other problems, since I only tested it with Python 3.5.

**Comment by SanskritFritz** [comment]
Thanks for your care!
I installed the git head version, it looks similar:
```
frank@HomeC ~> rednotebook 
Adding /usr/lib/python3.6/site-packages to sys.path
2017-05-23 15:34:41,438 INFO     Writing log to file "/home/frank/.rednotebook/rednotebook.log"
2017-05-23 15:34:41,438 INFO     System encoding: utf-8
2017-05-23 15:34:41,438 INFO     Language code: hu_HU
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 11, in <module>
    import rednotebook.journal
  File "/usr/lib/python3.6/site-packages/rednotebook/journal.py", line 149, in <module>
    from rednotebook.gui.main_window import MainWindow
  File "/usr/lib/python3.6/site-packages/rednotebook/gui/main_window.py", line 32, in <module>
    from rednotebook.gui.options import OptionsManager
  File "/usr/lib/python3.6/site-packages/rednotebook/gui/options.py", line 28, in <module>
    from rednotebook.gui import editor
  File "/usr/lib/python3.6/site-packages/rednotebook/gui/editor.py", line 27, in <module>
    from rednotebook.gui import t2t_highlight
  File "/usr/lib/python3.6/site-packages/rednotebook/gui/t2t_highlight.py", line 252, in <module>
    bullet_list = Pattern(r"^ *(\-) [^ ].*$", [(1, 'red'), (1, 'bold')], name='list')
  File "/usr/lib/python3.6/site-packages/rednotebook/gui/t2t_highlight.py", line 75, in __init__
    self._regexp = re.compile(pattern_or_regex, flag)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/lib/python3.6/sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

**Comment by SanskritFritz** [comment]
Yes, perfect, thank you! Waiting for a 2.1 version 😃 .
