### ISSUE TITLE
Update Windows installer to 2.*

### ISSUE THREAD

**Issue by GameMaker** [jendrikseipp/rednotebook#328]
Hi all -

I saw the news of a 2.0 release - exciting! Congrats!

When I went to the installer download page, only the .tar.gz was available. Is there a plan to release a .exe installer?

Thanks!

**Comment by jendrikseipp** [comment]
Porting to GTK 3 on Windows proved to be quite hard since the underlying webkit2gtk library doesn't support Windows. I will have to figure out an alternative before work on the port can continue. For the time being you can just keep using the last 1.x version. There are no new features in the 2.0 release.

**Comment by jendrikseipp** [comment]
I managed to port RedNotebook 2.x to Windows and created a new installer. It would be great if you could test this beta version and report any issues you find. Please backup your files beforehand.
 
https://sourceforge.net/projects/rednotebook/files/beta/rednotebook-2.2-r7d3ff09.exe/download

**Comment by thatscoteng** [comment]
I had a go at running this this morning. I initially got an error multiple times when running it:
![rednotebook error](https://user-images.githubusercontent.com/3950932/29553290-7b788f4a-8712-11e7-8b91-bcee64c3c53f.png)

I started to dig out the log file when it jumped into life and seems to be working fine now.

Log file attached:

[rednotebook.log.txt](https://github.com/jendrikseipp/rednotebook/files/1241116/rednotebook.log.txt)

I have since attempted to close and open a couple of times. It still shows the same error 4 times when launching however it does launch after all the messages have been dismissed.

**Comment by Peter-FB** [comment]
The beta version installed fine on Windows 10 (in VirtualBox). When I tried to start it I got this error:

Fatal Error! Error loading Python DLL: C:\Program Files (x86)\RedNotebook\python34.dll (error code 126)

I couldn't get it to start.

**Comment by Zaphod2012** [comment]
Backed up data from version 1.15, installed new version to same directory.

Initial run after installation went smooth, but old data not picked up, and no visible way to import old data.

Closed the application and started it again from QuickLaunch icon, but received this error message:

"Failed to execute script journal"

Here is the entire log:

2017-08-21 19:28:24,027 INFO     Writing log to file "C:\Users\USERNAME\.rednotebook\rednotebook.log"
2017-08-21 19:28:24,027 INFO     System encoding: mbcs
2017-08-21 19:28:24,027 INFO     Language code: en_US
2017-08-21 19:28:24,100 INFO     Using pyyaml for loading and dumping
2017-08-21 19:28:24,231 INFO     Running in portable mode: False
2017-08-21 19:28:24,231 INFO     First Start: False
2017-08-21 19:28:24,231 INFO     RedNotebook version: 2.1.5
2017-08-21 19:28:24,231 INFO     System info: machine: AMD64, platform: Windows-7-6.1.7601-SP1, processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD, python_version: 3.4.4, release: 7, system: Windows, GTK: (3, 18, 9), Glib: (2, 52, 1), PyGObject: (3, 18, 2), YAML: 3.10
2017-08-21 19:28:25,265 DEBUG    Default font: Segoe UI 9
2017-08-21 19:28:25,265 DEBUG    Default size: 9.0
2017-08-21 19:28:25,492 DEBUG    Tray icon visible: False
2017-08-21 19:28:25,494 INFO     Opening journal at 'C:\\Users\\USERNAME\\.rednotebook\\data'
2017-08-21 19:28:25,494 DEBUG    Starting to load files in dir "C:\Users\USERNAME\.rednotebook\data"
2017-08-21 19:28:25,495 DEBUG    Finished loading files in dir "C:\Users\USERNAME\.rednotebook\data"
Traceback (most recent call last):
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 583, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 570, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 221, in __init__
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 94, in check_new_version
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 80, in get_new_version_number
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
  File "C:\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python34\lib\urllib\request.py", line 1211, in http_open
  File "C:\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python34\lib\http\client.py", line 898, in send
  File "C:\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python34\lib\socket.py", line 498, in create_connection
  File "C:\Python34\lib\socket.py", line 537, in getaddrinfo
LookupError: unknown encoding: idna

**Comment by jendrikseipp** [comment]
Thanks for testing! I have created a new beta that hopefully fixes the errors you've seen: https://sourceforge.net/projects/rednotebook/files/beta/rednotebook-2.2-beta2.exe/download

Does it start and run for you? Does the spell checking work?

**Comment by Peter-FB** [comment]
Hi Jendrick,

I tested the new beta with Windows 10 (in VirtualBox) and it seems to work fine. Spell checking also seems to work. The only thing that I noticed is that the width of the scrollbar is really tiny.

Vielen lieben Dank! :) It probably was a lot of work to port the new version to Windows.

**Comment by Zaphod2012** [comment]
Installed Beta 2 and all appears to be working properly again! :)

Thank You so much, Jendrik :)

One suggestion: It would be nice for new users if there were an **Import** feature to automagically grab the data from your .zip backups and add it to a new installation - It's a simple matter to unzip the file to the data folder, but a lot of folks might not know to do that...

**Comment by jendrikseipp** [comment]
@Peter-FB Yes, it was a lot of work, indeed :-)

@Zaphod2012 Importing zips would be a nice feature to have. It's on the TODO list :-)

Thanks again for testing!

**Comment by thatscoteng** [comment]
Thanks @jendrikseipp 

I can confirm the error I was viewing earlier is no longer appearing and that spell checking works.

Thanks again.

**Comment by jendrikseipp** [comment]
I released version 2.2 and included the new installer. You can find it at https://github.com/jendrikseipp/rednotebook/releases.
