### ISSUE TITLE
Cannot read 08 and 09 days numbers

### ISSUE THREAD

**Issue by Nick222** [jendrikseipp/rednotebook#332]
Xubuntu 17.04-64
RNB 2.0 from daily PPA

I convert by text editor my old notes (from another source) in month file for RNB and copy it in my journal directory.

When days was 08 and 09 - RNB cannot start and say that it cannot read integer variable.
After change days to 8 and 9 - RNB start good.

**Comment by Nick222** [comment]
Coping from terminal:

> rednotebook
Adding /usr/share/rednotebook to sys.path
2017-07-07 11:10:59,774 INFO     Writing log to file "/home/nick/.rednotebook/rednotebook.log"
2017-07-07 11:10:59,774 INFO     System encoding: utf-8
2017-07-07 11:10:59,774 INFO     Language code: ru_RU
2017-07-07 11:10:59,902 INFO     Running in portable mode: False
2017-07-07 11:10:59,902 INFO     First Start: False
2017-07-07 11:10:59,902 INFO     RedNotebook version: 2.0
2017-07-07 11:10:59,906 INFO     System info: machine: x86_64, platform: Linux-4.10.0-26-generic-x86_64-with-Ubuntu-17.04-zesty, processor: x86_64, python_version: 3.5.3, release: 4.10.0-26-generic, system: Linux, GTK: (3, 22, 11), Glib: (2, 52, 0), PyGObject: (3, 22, 0), YAML: 3.12
2017-07-07 11:11:00,177 DEBUG    Default font: Noto Sans 10
2017-07-07 11:11:00,178 DEBUG    Default size: 10.0
2017-07-07 11:11:00,351 INFO     Cloud ignore list: []
2017-07-07 11:11:00,351 INFO     Cloud include list: []
2017-07-07 11:11:00,351 DEBUG    Start compiling regexes
2017-07-07 11:11:00,351 DEBUG    Finished
2017-07-07 11:11:00,402 DEBUG    Tray icon visible: False
2017-07-07 11:11:00,403 INFO     Opening journal at '/home/nick/D1_Черновики/RedNotebook'
2017-07-07 11:11:00,403 DEBUG    Starting to load files in dir "/home/nick/D1_Черновики/RedNotebook"
2017-07-07 11:11:00,404 DEBUG    .directory is not a valid month filename
2017-07-07 11:11:00,404 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2011-06.txt"
2017-07-07 11:11:00,406 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2011-07.txt"
2017-07-07 11:11:00,410 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2011-08.txt"
2017-07-07 11:11:00,412 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2011-09.txt"
2017-07-07 11:11:00,414 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2011-12.txt"
2017-07-07 11:11:00,418 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-01.txt"
2017-07-07 11:11:00,419 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-02.txt"
2017-07-07 11:11:00,422 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-03.txt"
2017-07-07 11:11:00,425 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-04.txt"
2017-07-07 11:11:00,428 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-05.txt"
2017-07-07 11:11:00,432 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-06.txt"
2017-07-07 11:11:00,435 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-07.txt"
2017-07-07 11:11:00,439 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-08.txt"
2017-07-07 11:11:00,443 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-09.txt"
2017-07-07 11:11:00,447 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-10.txt"
2017-07-07 11:11:00,451 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-11.txt"
2017-07-07 11:11:00,455 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2012-12.txt"
2017-07-07 11:11:00,460 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-01.txt"
2017-07-07 11:11:00,464 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-02.txt"
2017-07-07 11:11:00,468 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-03.txt"
2017-07-07 11:11:00,472 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-04.txt"
2017-07-07 11:11:00,474 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-07.txt"
2017-07-07 11:11:00,477 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-08.txt"
2017-07-07 11:11:00,478 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2013-09.txt"
2017-07-07 11:11:00,480 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2015-09.txt"
2017-07-07 11:11:00,480 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2016-07.txt"
2017-07-07 11:11:00,481 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2016-08.txt"
2017-07-07 11:11:00,483 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2016-09.txt"
2017-07-07 11:11:00,484 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2016-10.txt"
2017-07-07 11:11:00,485 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2016-11.txt"
2017-07-07 11:11:00,486 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2016-12.txt"
2017-07-07 11:11:00,488 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-01.txt"
2017-07-07 11:11:00,491 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-02.txt"
2017-07-07 11:11:00,494 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-03.txt"
2017-07-07 11:11:00,497 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-04.txt"
2017-07-07 11:11:00,499 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-05.txt"
2017-07-07 11:11:00,502 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-06.txt"
2017-07-07 11:11:00,506 DEBUG    Loading file "/home/nick/D1_Черновики/RedNotebook/2017-07.txt"
2017-07-07 11:11:00,507 ERROR    An error occured while reading /home/nick/D1_Черновики/RedNotebook/2017-07.txt:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ImportError: No module named 'journal'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.journal.main()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 552, in main
    journal = Journal()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 196, in __init__
    self.open_journal(journal_path)
  File "/usr/share/rednotebook/rednotebook/journal.py", line 324, in open_journal
    self.months = storage.load_all_months_from_disk(data_dir)
  File "/usr/share/rednotebook/rednotebook/storage.py", line 99, in load_all_months_from_disk
    month = _load_month_from_disk(path, year_number, month_number)
  File "/usr/share/rednotebook/rednotebook/storage.py", line 76, in _load_month_from_disk
    month = Month(year_number, month_number, month_contents, os.path.getmtime(path))
  File "/usr/share/rednotebook/rednotebook/data.py", line 265, in __init__
    self.days[day_number] = Day(self, day_number, day_content)
  File "/usr/share/rednotebook/rednotebook/data.py", line 92, in __init__
    self.date = datetime.date(month.year_number, month.month_number, day_number)
TypeError: an integer is required (got type str)

**Comment by jendrikseipp** [comment]
Well, your first comment describes the solution :-)
