### ISSUE TITLE
"Unknown encoding" error when launching Rednotebook

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#35]
Below is the log displayed when running Rednotebook from command line. FYI, I use Tamil (ta) as system language.
I could make the rednotebook run successfully by changing line no. 61 to "locale_encoding = 'UTF-8'" in "/usr/share/rednotebook/rednotebook/util/dates.py". Let us fix this permanently.

INFO     Writing log to file "/home/murali/.rednotebook/rednotebook.log"
INFO     MathJax location: http://cdn.mathjax.org/mathjax/latest/MathJax.js
INFO     Running in portable mode: False
INFO     First Start: False
INFO     RedNotebook version: 1.4.0
INFO     System info: machine: x86_64, platform: Linux-3.13.0-30-generic-x86_64-with-Ubuntu-14.04-trusty, processor: x86_64, python_version: 2.7.6, release: 3.13.0-30-generic, system: Linux, GTK version: (2, 24, 23), PyGTK version: (2, 24, 0), Yaml version: 3.10
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.journal.main()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 606, in main
    journal = Journal()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 244, in __init__
    self.frame = MainWindow(self)
  File "/usr/share/rednotebook/rednotebook/gui/main_window.py", line 130, in __init__
    self.export_assistant = ExportAssistant(self.journal)
  File "/usr/share/rednotebook/rednotebook/gui/exports.py", line 333, in __init__
    self.page3 = ContentsPage(self.journal, self)
  File "/usr/share/rednotebook/rednotebook/gui/exports.py", line 126, in __init__
    self.date_format = options.DateFormatOption(_('Date format'), 'exportDateFormat')
  File "/usr/share/rednotebook/rednotebook/gui/options.py", line 175, in __init__
    self.on_format_changed(None)
  File "/usr/share/rednotebook/rednotebook/gui/options.py", line 179, in on_format_changed
    date_string = dates.format_date(format_string)
  File "/usr/share/rednotebook/rednotebook/util/dates.py", line 62, in format_date
    date_string = date_string.decode(locale_encoding, 'replace')
LookupError: unknown encoding: TSCII-0

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2014-08-03T17:23:18Z):

----------------------------------------

This issue has already been fixed. Please update to a newer version.
