### ISSUE TITLE
Issue in add_instruction_content on first start

### ISSUE THREAD

**Issue by bitmuster** [jendrikseipp/rednotebook#389]
Hi, thanks a lot for developing RedNotebook i use it already for quite some time.

### Versions
RedNotebook version: Current master: 960d57b2c5879d0d9669ebc3d41ff6a258a3362c
Operating system and version: Debian stretch 9.3

### Expected behavior
Gui opens when directory ~/.rednotebook is not there (i.e. first start)

### Actual behavior

Seemed like it tries to update a search index that is not yet there while executing
add_instruction_content.
See log below.

### Steps to reproduce the behavior

use fresh account or delete .rednotebook folder & start

### Log output when reproducing behavior

```
micha@proteus:~/.rednotebook$ cat rednotebook.log 
2018-01-08 22:06:32,036 INFO     Writing log to file "/home/micha/.rednotebook/rednotebook.log"
2018-01-08 22:06:32,036 INFO     System encoding: utf-8
2018-01-08 22:06:32,037 INFO     Language code: en_US
2018-01-08 22:06:32,207 WARNING  For spell checking, please install enchant (python3-enchant).
2018-01-08 22:06:32,333 INFO     Running in portable mode: False
2018-01-08 22:06:32,334 INFO     First Start: True
2018-01-08 22:06:32,334 INFO     RedNotebook version: 2.3
2018-01-08 22:06:32,344 INFO     System info: machine: x86_64, platform: Linux-4.9.0-5-amd64-x86_64-with-debian-9.3, processor: , python_version: 3.5.3, release: 4.9.0-5-amd64, system: Linux, GTK: (3, 22, 11), Glib: (2, 50, 3), PyGObject: (3, 22, 0), YAML: 3.12
2018-01-08 22:06:33,169 DEBUG    Default font: Sans 10
2018-01-08 22:06:33,170 DEBUG    Default size: 10.0
2018-01-08 22:06:33,465 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2018-01-08 22:06:33,465 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
2018-01-08 22:06:33,465 DEBUG    Start compiling regexes
2018-01-08 22:06:33,466 DEBUG    Finished
2018-01-08 22:06:33,545 DEBUG    Tray icon visible: False
2018-01-08 22:06:33,548 INFO     Opening journal at '/home/micha/.rednotebook/data'
2018-01-08 22:06:33,549 DEBUG    Starting to load files in dir "/home/micha/.rednotebook/data"
2018-01-08 22:06:33,550 DEBUG    Finished loading files in dir "/home/micha/.rednotebook/data"
2018-01-08 22:06:33,552 INFO     Adding example content on 2018-01-08
Traceback (most recent call last):
  File "rednotebook/journal.py", line 599, in <module>
    main()
  File "rednotebook/journal.py", line 581, in main
    journal = Journal()
  File "rednotebook/journal.py", line 216, in __init__
    self.open_journal(journal_path)
  File "rednotebook/journal.py", line 354, in open_journal
    self.add_instruction_content()
  File "rednotebook/journal.py", line 574, in add_instruction_content
    self.go_to_next_day()
  File "rednotebook/journal.py", line 462, in go_to_next_day
    following_edited_days = self.get_days_in_date_range(start_date=next_date)
  File "rednotebook/journal.py", line 556, in get_days_in_date_range
    for day in self.days:
  File "rednotebook/journal.py", line 534, in days
    self.save_old_day()
  File "rednotebook/journal.py", line 408, in save_old_day
    self.search_index.remove(self.day.date, self.day.get_indexed_words())
  File "/home/micha/Dump/Notebook/rednotebook/rednotebook/index.py", line 33, in remove
    self._word_to_dates[word].remove(date)
KeyError: datetime.date(2018, 1, 8)
micha@proteus:~/.rednotebook$ 
```

### Fix available

I already made a small fix that updates the search index while the template data is added.
When you like it, please pull from the repo below.

I'm going to create a pull request from here:
https://github.com/bitmuster/rednotebook
Branch : fix_empty_journal

While investigating I wrote two new tests to narrow down the problem.
One of them is a really ugly and complex one but I saw no other option to work around existing dependencies. I leave it up to you to take it, too.

Best Regards, Michael

**Comment by jendrikseipp** [comment]
Thanks again for your work on this, I just merged your patch.
