### ISSUE TITLE
RedNotebook 2.9 crashing on Windows 10

### ISSUE THREAD

**Issue by MBDamage** [jendrikseipp/rednotebook#430]
### Versions

RedNotebook version (make sure you have the latest version): 2.9

Operating system and version: 
Windows 10 Enterprise
Version 1703
OS Build 15063.1689

### Expected behavior
Software will run without crashing. 

I have used this software for the past few months and it was great until I upgraded from version 2.8 to version 2.9 a few days ago. 

### Actual behavior
Software crashes and or the product won't open until I completely restart my system. I may 

### Steps to reproduce the behavior
I just need to use the software and it will eventually crash. Once the crash happens it will continue to crash until it will not open. The only way to get it to work again is to reboot the machine. 

### Log output when reproducing behavior
2019-03-20 21:32:40,595 INFO     Writing log to file "C:\Users\Dave\.rednotebook\rednotebook.log"
2019-03-20 21:32:40,595 INFO     System encoding: utf-8
2019-03-20 21:32:40,595 INFO     Language code: en_NZ
2019-03-20 21:32:40,725 INFO     Running in portable mode: False
2019-03-20 21:32:40,725 INFO     First Start: False
2019-03-20 21:32:40,725 INFO     RedNotebook version: 2.9
2019-03-20 21:32:40,725 INFO     System info: machine: AMD64, platform: Windows-10-10.0.15063-SP0, processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel, python_version: 3.6.8, release: 10, system: Windows, GTK: (3, 22, 30), Glib: (2, 58, 1), PyGObject: (3, 28, 3), YAML: 3.13
2019-03-20 21:32:41,585 DEBUG    Default font: Sans 10
2019-03-20 21:32:41,585 DEBUG    Default size: 10.0
2019-03-20 21:32:41,594 WARNING  no installed dictionary for language "en_NZ" and english, fallback to first language in language list ("de_DE")
2019-03-20 21:32:42,048 DEBUG    Tray icon visible: False
2019-03-20 21:32:42,051 INFO     Opening journal at 'E:\\My Journal'
2019-03-20 21:32:42,051 DEBUG    Starting to load files in dir "E:\My Journal"
2019-03-20 21:32:42,052 DEBUG    Loading file "E:\My Journal\2019-03.txt"
2019-03-20 21:32:42,054 DEBUG    Finished loading files in dir "E:\My Journal"
2019-03-20 21:32:42,128 INFO     Connected Signals: [<Signals.SIGINT: 2>, <Signals.SIGABRT: 22>, <Signals.SIGTERM: 15>]
2019-03-20 21:32:42,129 DEBUG    Start took 1.404733657836914 seconds
2019-03-20 21:32:42,129 DEBUG    Trying to enter the gtk main loop
2019-03-20 21:32:42,676 INFO     Last backup was made 27 days ago
2019-03-20 21:32:43,648 INFO     2.9 is the latest version
2019-03-20 21:32:43,648 INFO     Current version: 2.9, latest version: 2.9, newer: False
[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "C:\repo\rednotebook\external\spellcheck.py", line 596, in _range_delete
  File "C:\repo\rednotebook\external\spellcheck.py", line 445, in check_range
  File "C:\repo\rednotebook\external\spellcheck.py", line 623, in _check_word
AttributeError: 'NoneType' object has no attribute 'strip'

Cheers,
MBDamgae

**Comment by jendrikseipp** [comment]
Thanks for reporting this. I was able to confirm that the CEF browser that's used for the previews doesn't work correctly on Windows 10. I just released a version that doesn't use CEF and instead makes the previews in an external browser. Could you please try out this version and report if the app works?

https://github.com/jendrikseipp/rednotebook/releases/tag/v2.9.1

**Comment by MBDamage** [comment]
Thanks heaps for correcting that. I have used it a few times since the update and all looks good.

I have do have another question for you. Why does the spell checker identify some words wrong when they are clearly correct.
An example would be the word “don’t”. The checker will underline the “‘t” as incorrect.

Cheers,
Dave

On 21/03/2019, at 03:48, Jendrik Seipp <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting this. I was able to confirm that the CEF browser that's used for the previews doesn't work correctly on Windows 10. I just released a version that doesn't use CEF and instead makes the previews in an external browser. Could you please try out this version and report if the app works?

https://github.com/jendrikseipp/rednotebook/releases/tag/v2.9.1

**Comment by jendrikseipp** [comment]
Sorry, I don't have an answer for you regarding the spell checker. Unfortunately, this can't be fixed in RedNotebook but we will have to wait for the underlying libraries to get fixed, I guess.

**Comment by MBDamage** [comment]
Thanks heaps for your help and reply.

Cheers,
Dave

On 27/03/2019, at 06:45, Jendrik Seipp <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I don't have an answer for you regarding the spell checker. Unfortunately, this can't be fixed in RedNotebook but we will have to wait for the underlying libraries to get fixed, I guess.

**Comment by jendrikseipp** [comment]
I reverted to the old GTK 3.18 stack in version 2.11. Can you confirm that the internal preview works again?
