### ISSUE TITLE
Rednotebook on mac osx via macports

### ISSUE THREAD

**Issue by Melbourne76** [jendrikseipp/rednotebook#446]
### Versions

RedNotebook version (make sure you have the latest version):

Operating system and version:

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.

**Comment by Melbourne76** [comment]
Hi ,

I have installed red notebook on my MacBook os x version 10.14.5 macOS Mojave.

I did so via macports.

Wehn I launch red notebook I get the following error:

Traceback (most recent call last):
  File "/opt/local/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/bin/rednotebook", line 11, in <module>
    import rednotebook.journal
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rednotebook/journal.py", line 166, in <module>
    from rednotebook.gui.main_window import MainWindow
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rednotebook/gui/main_window.py", line 32, in <module>
    from rednotebook.gui.options import OptionsManager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rednotebook/gui/options.py", line 28, in <module>
    from rednotebook.gui import editor
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rednotebook/gui/editor.py", line 39, in <module>
    DEFAULT_FONT = Gtk.Settings.get_default().get_property('gtk-font-name')
AttributeError: 'NoneType' object has no attribute 'get_property'

The version that was downloaded by macports is : 

RedNotebook 2.3

I read a post on git that sounded similar. I think the solution was to update to red notebook2.8.

It isn't clear how to select the version that you download via macports.

Can  I get some help so that I can make use of this tool on my MacBook air ?

thanks

**Comment by jendrikseipp** [comment]
Sorry, I don't have a Mac and don't know anything about MacPorts, so I can't offer any help. FWIW, the error message hints at the fact that GTK isn't installed properly.

**Comment by Melbourne76** [comment]
Okay. Nevertheless thanks for the hint
