### ISSUE TITLE
can't insert template

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#49]
rednotebook 0.9.3 windows
Nothing happened after click the insert template icon.

rednotebook.log
==================================================
INFO     Writing log to file "C:\Documents and Settings\neo\.rednotebook\rednotebook.log"
ERROR    'module' object has no attribute 'bindtextdomain'
INFO     Using libyaml for loading and dumping
INFO     AppDir: C:\Program Files\RedNotebook
INFO     BaseDir: C:\Program Files
INFO     Adding BaseDir to sys.path
INFO     webkit not found. For a nicer preview install python-webkit or pywebkitgtk
INFO     The config file C:\Program Files\RedNotebook\files\default.cfg was read
INFO     The config file C:\Documents and Settings\neo\.rednotebook\configuration.cfg was read
INFO     Running in portable mode: 0
INFO     First Start: False
INFO     RedNotebook version: 0.9.3
INFO     System info: machine: x86, platform: Windows-XP-5.1.2600-SP2, processor: x86 Family 6 Model 15 Stepping 13, GenuineIntel, python_version: 2.6.4, release: XP, system: Windows, GTK version: (2, 16, 6), PyGTK version: (2, 16, 0), Yaml version: 3.09, 
INFO     Using webkit: None
WARNING  pywebkitgtk is not installed. You may experience errors
INFO     Cloud ignore list: ['comma', 'filter', 'separated', 'these', 'words']
INFO     Cloud include list: ['job', 'mtv', 'play', 'spam', 'work']
INFO     Using zeitgeist: False
INFO     Opening journal at C:\Documents and Settings\neo\.rednotebook\data
INFO     Connected Signals: 2 22 15 
INFO     Trying to save the journal
INFO     Nothing to save
INFO     Goodbye!
s not installed. You may experience errors
2010-03-13 18:56:26,187 INFO     Cloud ignore list: ['comma', 'filter', 'separated', 'these', 'words']
2010-03-13 18:56:26,187 INFO     Cloud include list: ['job', 'mtv', 'play', 'spam', 'work']
2010-03-13 18:56:26,217 DEBUG    Tray icon visible: False
2010-03-13 18:56:26,217 INFO     Using zeitgeist: False
2010-03-13 18:56:26,217 INFO     Opening journal at C:\Documents and Settings\neo\.rednotebook\data
2010-03-13 18:56:26,217 DEBUG    Starting to load files in dir "C:\Documents and Settings\neo\.rednotebook\data"
2010-03-13 18:56:26,217 DEBUG    Start loading file "C:\Documents and Settings\neo\.rednotebook\data\2010-03.txt"
2010-03-13 18:56:26,233 DEBUG    Finished loading file "C:\Documents and Settings\neo\.rednotebook\data\2010-03.txt"
2010-03-13 18:56:26,233 DEBUG    Finished loading files in dir "C:\Documents and Settings\neo\.rednotebook\data"
2010-03-13 18:56:26,265 DEBUG    Update the cloud (Type: word, Force: True)
2010-03-13 18:56:26,265 DEBUG    Retrieved WordCountDict. Length: 274
2010-03-13 18:56:26,265 DEBUG    Turning the wordCountDict into html
2010-03-13 18:56:26,265 DEBUG    Length wordCountDict: 274
2010-03-13 18:56:26,265 DEBUG    Filtered short words. Length wordCountDict: 145
2010-03-13 18:56:26,265 DEBUG    Filtered blacklist words. Length wordCountDict: 145
2010-03-13 18:56:26,265 DEBUG    Selected most frequent words. Length CloudWords: 42
2010-03-13 18:56:26,265 DEBUG    Min word count: 1, Max word count: 10
2010-03-13 18:56:26,265 DEBUG    Sorted cloud words. Length CloudWords: 42
2010-03-13 18:56:26,265 DEBUG    42 cloud words found
2010-03-13 18:56:26,280 DEBUG    Cloud updated
2010-03-13 18:56:26,296 INFO     Connected Signals: 2 22 15 
2010-03-13 18:56:26,296 DEBUG    Start took 1.09299993515 seconds
2010-03-13 18:56:26,296 DEBUG    Trying to enter the gtk main loop
C:\Program Files\RedNotebook\rednotebook.exe\rednotebook\redNotebook.py:997: PangoWarning: couldn't load font "Tahoma Ultra-Bold Small-Caps 17.279296875", falling back to "Sans Ultra-Bold Small-Caps 17.279296875", expect ugly output.
C:\Program Files\RedNotebook\rednotebook.exe\rednotebook\redNotebook.py:997: PangoWarning: couldn't load font "Sans Ultra-Bold Small-Caps 17.279296875", falling back to "Sans 17.279296875", expect ugly output.
Traceback (most recent call last):
  File "rednotebook\gui\mainWindow.pyc", line 612, in on_templateMenu_clicked
  File "rednotebook\templates.pyc", line 189, in get_weekday_text
  File "rednotebook\templates.pyc", line 175, in get_text
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: invalid data
2010-03-13 18:56:32,655 INFO     Trying to save the journal
2010-03-13 18:56:32,655 INFO     Nothing to save
2010-03-13 18:56:32,655 INFO     Goodbye!
======================================================

configuration.cfg
======================================================
checkForNewVersion=0
cloudIgnoreList=comma, filter, separated, these, words
spellcheck=0
rightDividerPosition=479
cloudIncludeList=job, mtv, play, spam, work
closeToTray=0
mainFontSize=-1
mainFrameWidth=1024
dataDir=C:\Documents and Settings\neo\.rednotebook\data
useWebkit=0
dateTimeString=%A, %x %X
mainFrameHeight=768
leftDividerPosition=292

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-04-25T12:27:30Z):

----------------------------------------

Hi, I have tried to fix the issue. Can you try out the 0.9.4 beta and tell me if it works?

http://dl.dropbox.com/u/4780737/rednotebook-0.9.4b-win32.exe

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-04-29T19:17:09Z):

----------------------------------------

Hopefully fixed in 0.9.4.

**Comment by jendrikseipp** [comment]
*Original comment by* **kloswerkes** (2010-12-28T19:52:01Z):

----------------------------------------

This is still happening in Version 1.1.2 on Windows, Portable version.  Here is the dump from the debug log:

DEBUG    sys.stdout logging level: 10
INFO     Writing log to file "H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\rednotebook.log"
DEBUG    LANG: None
DEBUG    Default locale: en_US
INFO     Set default locale: "en_US"
INFO     Setting LANG to en_US
INFO     Module glade found
INFO     'module' object has no attribute 'bindtextdomain'
INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\configuration.cfg
INFO     Running in portable mode: True
DEBUG    Debug Mode is on
INFO     First Start: False
INFO     RedNotebook version: 1.1.2
INFO     System info: machine: x86, platform: Windows-XP-5.1.2600-SP3, processor: x86 Family 6 Model 23 Stepping 10, GenuineIntel, python_version: 2.6.4, release: XP, system: Windows, GTK version: (2, 20, 0), PyGTK version: (2, 16, 0), Yaml version: 3.09
INFO     Using webkit for previews: True
INFO     Cloud ignore list: ['comma', 'filter', 'separated', 'these', 'words']
INFO     Cloud include list: ['job', 'mtv', 'play', 'spam', 'work']
INFO     Using pywebkitgtk for the clouds.
DEBUG    Tray icon visible: False
INFO     Using zeitgeist: False
INFO     Opening journal at H:\Logs\Daily\Journal\MainJournal\RedNoteBook
DEBUG    Starting to load files in dir "H:\Logs\Daily\Journal\MainJournal\RedNoteBook"
DEBUG    Start loading file "H:\Logs\Daily\Journal\MainJournal\RedNoteBook\2010-12.txt"
DEBUG    Finished loading file "H:\Logs\Daily\Journal\MainJournal\RedNoteBook\2010-12.txt"
DEBUG    Finished loading files in dir "H:\Logs\Daily\Journal\MainJournal\RedNoteBook"
DEBUG    Update the cloud (Type: word, Force: True)
DEBUG    Retrieved WordCountDict. Length: 235
DEBUG    Turning the word_count_dict into html
DEBUG    Length word_count_dict: 235
DEBUG    Filtered short words. Length word_count_dict: 142
DEBUG    Filtered blacklist words. Length word_count_dict: 142
DEBUG    Selected most frequent words. Length CloudWords: 42
DEBUG    Min word count: 1, Max word count: 23
DEBUG    Sorted cloud words. Length CloudWords: 42
DEBUG    42 cloud words found
DEBUG    Cloud updated
INFO     Connected Signals: 2 22 15 
DEBUG    Start took 3.57800006866 seconds
DEBUG    Trying to enter the gtk main loop
INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\templates\1.txt
INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\templates\1.txt
INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\templates\HelpdeskIssue.txt
s. Length CloudWords: 42
2010-12-28 13:44:24,579 DEBUG    Min word count: 1, Max word count: 23
2010-12-28 13:44:24,579 DEBUG    Sorted cloud words. Length CloudWords: 42
2010-12-28 13:44:24,579 DEBUG    42 cloud words found
2010-12-28 13:44:24,579 DEBUG    Cloud updated
2010-12-28 13:44:24,595 INFO     Connected Signals: 2 22 15 
2010-12-28 13:44:24,595 DEBUG    Start took 3.57800006866 seconds
2010-12-28 13:44:24,595 DEBUG    Trying to enter the gtk main loop
2010-12-28 13:45:29,841 INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\templates\1.txt
Traceback (most recent call last):
  File "rednotebook\gui\main_window.pyc", line 666, in on_template_menu_clicked
  File "rednotebook\templates.pyc", line 185, in get_weekday_text
  File "rednotebook\templates.pyc", line 168, in get_text
LookupError: unknown encoding: Tuesday, 12/28/2010 1:45:29 PM
2010-12-28 13:45:30,404 INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\templates\1.txt
Traceback (most recent call last):
  File "rednotebook\gui\main_window.pyc", line 666, in on_template_menu_clicked
  File "rednotebook\templates.pyc", line 185, in get_weekday_text
  File "rednotebook\templates.pyc", line 168, in get_text
LookupError: unknown encoding: Tuesday, 12/28/2010 1:45:30 PM
2010-12-28 13:50:17,910 INFO     Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for H:\Logs\Daily\Journal\RedNotebookPortable\App\RedNotebook\user\templates\HelpdeskIssue.txt

--

Is it having a problem with it being a Windows text file?

**Comment by jendrikseipp** [comment]
*Original comment by* **kai-dehrmann** (2010-12-30T16:35:55Z):

----------------------------------------

Same thing is happening on Ubuntu 10.10 !

Does not seem to be a Windows specific problem

Kind regards

Kai Dehrmann
<email address hidden>

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-01-07T13:55:57Z):

----------------------------------------

The issue that Michael and Kai experienced is caused by a different bug. This should be fixed in the latest beta http://dl.dropbox.com/u/4780737/rednotebook-1.1.3-b1-win32.exe 

 Can you confirm that Michael?

**Comment by jendrikseipp** [comment]
*Original comment by* **kai-dehrmann** (2011-01-07T21:23:25Z):

----------------------------------------

Am 07.01.2011 14:55, schrieb Jendrik Seipp:
> The issue that Michael and Kai experienced is caused by a different bug.
> This should be fixed in the latest beta
> http://dl.dropbox.com/u/4780737/rednotebook-1.1.3-b1-win32.exe
>
>   Can you confirm that Michael?
>
Hello Jendrik,

this latest beta version 1.1.3 works fine under :

- Linux Mint 10 ( = Ubuntu 10.10) with wine
- Windows XP (SP3)

regarding insertion of templates.

Kind regards

Kai
