### ISSUE TITLE
Rednotebook does not work with Turkish locale

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#50]
Binary package hint: rednotebook

As described in the title when we try to open Rednotebook with Turkish locale we get this error:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.redNotebook.main()
  File "/usr/share/rednotebook/rednotebook/redNotebook.py", line 985, in main
    redNotebook = RedNotebook()
  File "/usr/share/rednotebook/rednotebook/redNotebook.py", line 286, in __init__
    self.frame = MainWindow(self)
  File "/usr/share/rednotebook/rednotebook/gui/mainWindow.py", line 156, in __init__
    self.setup_format_menu()
  File "/usr/share/rednotebook/rednotebook/gui/mainWindow.py", line 655, in setup_format_menu
    ('Underline', _('Underline')))] \
  File "/usr/share/rednotebook/rednotebook/gui/mainWindow.py", line 643, in get_action
    return (format, getattr(gtk, 'STOCK_' + format.upper()), \
AttributeError: 'module' object has no attribute 'STOCK_ITALiC'

I think this is because of STOCK_ITALiC part.

When we start Rednotebook like that the application is successfuly opened. 

LC_ALL=C rednotebook

ProblemType: Crash
DistroRelease: Ubuntu 10.04
Package: rednotebook 0.9.2-1
ProcVersionSignature: Ubuntu 2.6.32-19.28-generic 2.6.32.10+drm33.1
Uname: Linux 2.6.32-19-generic x86_64
NonfreeKernelModules: nvidia
Architecture: amd64
CheckboxSubmission: 2d318cb415d02b5308568dbff5236c6c
CheckboxSystem: 8747e013a552447cbd294fa2163135be
Date: Mon Apr  5 03:28:24 2010
ExecutablePath: /usr/share/rednotebook/run.py
InterpreterPath: /usr/bin/python2.6
PackageArchitecture: all
ProcCmdline: /usr/bin/python /usr/bin/rednotebook
ProcEnviron:
 PATH=(custom, user)
 LANG=tr_TR.UTF-8
 SHELL=/bin/bash
PythonArgs: ['/usr/bin/rednotebook']
SourcePackage: rednotebook
Title: run.py crashed with AttributeError in get_action()
UserGroups: adm admin cdrom dialout lpadmin plugdev pulse pulse-access sambashare vboxusers

**Comment by jendrikseipp** [comment]
*Original comment by* **heartsmagic** (2010-04-05T00:34:22Z):

----------------------------------------

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-09T22:15:21Z):

----------------------------------------

Hi,

Thanks for reporting this bug. I can't reproduce it on a clean Lucid system; please send me the output of `locale` from a terminal.

Thanks.

**Comment by jendrikseipp** [comment]
*Original comment by* **heartsmagic** (2010-07-09T23:39:53Z):

----------------------------------------

Here is the locale output:

LANG=tr_TR.UTF-8
LC_CTYPE="tr_TR.UTF-8"
LC_NUMERIC="tr_TR.UTF-8"
LC_TIME="tr_TR.UTF-8"
LC_COLLATE="tr_TR.UTF-8"
LC_MONETARY="tr_TR.UTF-8"
LC_MESSAGES="tr_TR.UTF-8"
LC_PAPER="tr_TR.UTF-8"
LC_NAME="tr_TR.UTF-8"
LC_ADDRESS="tr_TR.UTF-8"
LC_TELEPHONE="tr_TR.UTF-8"
LC_MEASUREMENT="tr_TR.UTF-8"
LC_IDENTIFICATION="tr_TR.UTF-8"
LC_ALL=


As a reference please see this bug:
https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/581207

As explained there:
"TEST CASE:
1. install turkish locale:
  $ sudo apt-get install language-pack-gnome-tr-base
2. from a terminal run the following command and note any error message:
  $ sudo LC_ALL=tr_TR.UTF8 update-software-center"

You can test this via:
LC_ALL=tr_TR.UTF8 rednotebook

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-10T17:48:44Z):

----------------------------------------

Confirmed in both 0.9.2 and 1.0.0

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-10T22:27:58Z):

----------------------------------------

This patch fixes the problem at startup, but there are still problems when doing a Category search from the cloud box.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-07-10T23:14:24Z):

----------------------------------------

Thanks for looking into that Jonathan. I don't know whether it wouldn't be better to just explicitly call e.g. gtk.STOCK_ITALIC etc. directly instead of that lazy string concatenating...

Do you have an error message when doing a Category search from the cloud box?

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-10T23:23:43Z):

----------------------------------------

That might be better, yes.

Here's the error from a Category search while in tr_TR.UTF-8:

INFO     Connected Signals: 1 2 3 6 15 20 
ERROR    Sorry! Txt2tags aborted by an unknown error.
Please send the following Error Traceback to the author (<email address hidden>):

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/util/markup.py", line 233, in convert_to_pango
    body, toc = txt2tags.convert(txt, config)
  File "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 5181, in convert
    line = add_inline_tags(line)
  File "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 4679, in add_inline_tags
    if regex['font%s'%beauti.capitalize()].search(line):
KeyError: 'fontitalic'

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-07-11T01:03:01Z):

----------------------------------------

Thanks. The error log shows that of course all external libs and modules cannot be used correctly with tr_TR.UTF-8 either. Do you really think this can/should be fixed in RedNotebook? I think it would make the code less readable, and many modules would have to be checked...

In one thread (http://mail.python.org/pipermail/python-bugs-list/2005-October/030816.html) I read:
I'm not sure what to say to this. My only advice is to *not* set the global locale setting to TR_tr, but only do this when it comes to actually processsing text in an application.

Do you think setting LC to C when it is tr_TR could be a (really hacky) workaround?

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-11T11:28:55Z):

----------------------------------------

Ok, so there are mostly two problems (that I've found, I can't promise there aren't more):

1. trying to start with the Turkish locale crashes the whole application

I don't think it's fair to those who want to use RedNotebook in their locale to just disable it - either of these would fix it:
 - just hard code the GTK+ STOCK_* names instead of looping over them
 - the patch as attached, which is pretty small - though I have done some further work on it since then

Either way I don't mind patching the Debian and Ubuntu packages for the time being if you're not in a position to make a release yet.

2. the problem with category searching

This doesn't crash RedNotebook totally, it just puts some tracebacks into the category box, so it isn't critical - let's just accept that it's a known issue for the time being. If you can work out exactly what's going on (I got a bit lost following that part of the code) and it's txt2tags' fault, then it should be sent upstream for Aurelio to see.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-07-12T02:56:39Z):

----------------------------------------

I chose to "just hard code the GTK+ STOCK_* names instead of looping over them". The patch is in trunk. If you want, you can try it out (https://code.launchpad.net/~jendrikseipp/rednotebook/trunk).

If you want to, you can send the bug upstream to Aurelio. 

I don't know when I will be ready to make a release. It might take a while ;)

Thanks, Jendrik

**Comment by jendrikseipp** [comment]
*Original comment by* **jwiltshire** (2010-07-18T21:58:36Z):

----------------------------------------

Ok, thanks. I've patched it and I'm waiting for the release team to sync it over from Debian.

**Comment by jendrikseipp** [comment]
*Original comment by* **janitor** (2010-08-04T22:25:34Z):

----------------------------------------

This bug was fixed in the package rednotebook - 1.0.0-2

---------------
rednotebook (1.0.0-2) unstable; urgency=low

  * [e9808c] Enable quilt patch system and add dependency and
    README.source
  * [2968fb] New patch gtk-stock.patch to fix crash when in Turkish
    locale (Closes: #588664) (LP: #555425)
  * [32f521] Standards version 3.9.0 (no changes)
  * [102b43] Remove mention of textlive-latex-extra in the description
 -- Jonathan Wiltshire <email address hidden>   Sun, 11 Jul 2010 00:17:20 +0100
