### ISSUE TITLE
export function disabled on windows xp

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#53]
I install RedNotebook 1.1.1 on Windows XP SP2. The Backup works smooth, but when I select the export command, and select the destination and go on from step1 to step5, I have got no exported files. all formats including plain text, html, latex, and pdf are tried, and get on result.
I thought this might be a bug for rednotebook, has anybody else encounter this problem.
I addition, the windows xp is chinese edition.
Thank you in advance.
zhisheng yan

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-09-06T20:45:43Z):

----------------------------------------

Thanks for the report.

I cannot replicate the error on my system (win xp sp3). However another user has reported the same issue by mail and I have redirected him here. Can you please post your logfile from C:\Documents and Settings\.rednotebook?

**Comment by jendrikseipp** [comment]
*Original comment by* **yanzhisheng** (2010-09-07T00:11:25Z):

----------------------------------------

Jendrik Seipp,
Thank you for your reply. I select the destination for the pdf exporting, i.e. E:\, after finished, I find no pdf.
the following  is the C:\Documents and Settings\yanzhisheng\.rednotebook\rednotebook.log
INFO     Writing log to file "C:\Documents and Settings\yanzhisheng\.rednotebook\rednotebook.log"
INFO     Set default locale: "zh_CN"
INFO     Setting LANG to zh_CN
INFO     Module glade found
INFO     'module' object has no attribute 'bindtextdomain'
INFO     Running in portable mode: False
INFO     First Start: False
INFO     RedNotebook version: 1.1.1
INFO     System info: machine: x86, platform: Windows-XP-5.1.2600-SP2, processor: x86 Family 6 Model 15 Stepping 2, GenuineIntel, python_version: 2.6.4, release: XP, system: Windows, GTK version: (2, 20, 0), PyGTK version: (2, 16, 0), Yaml version: 3.09
INFO     Using webkit for previews: True
INFO     Cloud ignore list: ['\xe5\x88\x86\xe9\x9a\x94\xe7\x9a\x84', '\xe6\x96\x87\xe5\xad\x97', '\xe8\xbf\x87\xe6\xbb\xa4', '\xe8\xbf\x99\xe4\xba\x9b', '\xe9\x80\x97\xe5\x8f\xb7']
INFO     Cloud include list: ['mtv', '\xe5\x9e\x83\xe5\x9c\xbe\xe9\x82\xae\xe4\xbb\xb6', '\xe5\xa8\xb1\xe4\xb9\x90', '\xe5\xb7\xa5\xe4\xbd\x9c']
INFO     Using pywebkitgtk for the clouds.
INFO     Using zeitgeist: False
INFO     Opening journal at E:\My Documents\MyRedNoteBook
INFO     Connected Signals: 2 22 15 
INFO     The content has been saved to E:\My Documents\MyRedNoteBook
INFO     Exporting to PDF
ERROR    Error replacing $date$: "'utf8' codec can't decode bytes in position 0-1: invalid data"
INFO     The content has been saved to E:\My Documents\MyRedNoteBook
INFO     Cloud ignore list: ['\xe5\x88\x86\xe9\x9a\x94\xe7\x9a\x84', '\xe6\x96\x87\xe5\xad\x97', '\xe8\xbf\x87\xe6\xbb\xa4', '\xe8\xbf\x99\xe4\xba\x9b', '\xe9\x80\x97\xe5\x8f\xb7']
INFO     Cloud include list: ['mtv', '\xe5\x9e\x83\xe5\x9c\xbe\xe9\x82\xae\xe4\xbb\xb6', '\xe5\xa8\xb1\xe4\xb9\x90', '\xe5\xb7\xa5\xe4\xbd\x9c']
07 08:02:27,905 INFO     Using zeitgeist: False
2010-09-07 08:02:27,905 INFO     Opening journal at E:\My Documents\MyRedNoteBook
2010-09-07 08:02:27,921 DEBUG    Starting to load files in dir "E:\My Documents\MyRedNoteBook"
2010-09-07 08:02:27,937 DEBUG    Start loading file "E:\My Documents\MyRedNoteBook\2010-08.txt"
2010-09-07 08:02:27,953 DEBUG    Finished loading file "E:\My Documents\MyRedNoteBook\2010-08.txt"
2010-09-07 08:02:27,953 DEBUG    Start loading file "E:\My Documents\MyRedNoteBook\2010-09.txt"
2010-09-07 08:02:27,967 DEBUG    Finished loading file "E:\My Documents\MyRedNoteBook\2010-09.txt"
2010-09-07 08:02:27,967 DEBUG    Finished loading files in dir "E:\My Documents\MyRedNoteBook"
2010-09-07 08:02:27,967 DEBUG    Update the cloud (Type: word, Force: True)
2010-09-07 08:02:27,983 DEBUG    Retrieved WordCountDict. Length: 237
2010-09-07 08:02:27,983 DEBUG    Turning the word_count_dict into html
2010-09-07 08:02:27,983 DEBUG    Length word_count_dict: 237
2010-09-07 08:02:27,983 DEBUG    Filtered short words. Length word_count_dict: 125
2010-09-07 08:02:27,983 DEBUG    Filtered blacklist words. Length word_count_dict: 125
2010-09-07 08:02:27,983 DEBUG    Selected most frequent words. Length CloudWords: 42
2010-09-07 08:02:27,983 DEBUG    Min word count: 1, Max word count: 14
2010-09-07 08:02:27,983 DEBUG    Sorted cloud words. Length CloudWords: 42
2010-09-07 08:02:27,983 DEBUG    42 cloud words found
2010-09-07 08:02:28,000 DEBUG    Cloud updated
2010-09-07 08:02:28,000 INFO     Connected Signals: 2 22 15 
2010-09-07 08:02:28,000 DEBUG    Start took 3.29699993134 seconds
2010-09-07 08:02:28,000 DEBUG    Trying to enter the gtk main loop
2010-09-07 08:03:52,312 INFO     The content has been saved to E:\My Documents\MyRedNoteBook
2010-09-07 08:03:52,312 DEBUG    Update the cloud (Type: word, Force: True)
2010-09-07 08:03:52,312 DEBUG    Retrieved WordCountDict. Length: 312
2010-09-07 08:03:52,312 DEBUG    Turning the word_count_dict into html
2010-09-07 08:03:52,312 DEBUG    Length word_count_dict: 312
2010-09-07 08:03:52,312 DEBUG    Filtered short words. Length word_count_dict: 176
2010-09-07 08:03:52,312 DEBUG    Filtered blacklist words. Length word_count_dict: 176
2010-09-07 08:03:52,312 DEBUG    Selected most frequent words. Length CloudWords: 42
2010-09-07 08:03:52,312 DEBUG    Min word count: 2, Max word count: 14
2010-09-07 08:03:52,312 DEBUG    Sorted cloud words. Length CloudWords: 42
2010-09-07 08:03:52,328 DEBUG    42 cloud words found
2010-09-07 08:03:52,328 DEBUG    Cloud updated
2010-09-07 08:04:19,875 INFO     Exporting to PDF
2010-09-07 08:04:19,875 DEBUG    Selected Categories for Export: [u'Movies', u'Done', u'Tags', u'Cool Stuff', u'Todo', u'Ideas']
Traceback (most recent call last):
  File "rednotebook\gui\exports.pyc", line 356, in _on_close
  File "rednotebook\gui\exports.pyc", line 434, in export
  File "rednotebook\gui\exports.pyc", line 451, in export_pdf
  File "rednotebook\gui\exports.pyc", line 418, in get_export_string
  File "rednotebook\util\markup.pyc", line 91, in get_markup_for_day
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 2-3: invalid data
2010-09-07 08:06:00,765 DEBUG    Chardet guesses {'confidence': 1.0, 'encoding': 'ascii'} for C:\Documents and Settings\yanzhisheng\.rednotebook\templates\2.txt
2010-09-07 08:06:00,765 ERROR    Error replacing $date$: "'utf8' codec can't decode bytes in position 0-1: invalid data"
2010-09-07 08:06:33,530 INFO     The content has been saved to E:\My Documents\MyRedNoteBook
2010-09-07 08:06:33,530 DEBUG    Update the cloud (Type: word, Force: True)
2010-09-07 08:06:33,530 DEBUG    Retrieved WordCountDict. Length: 312
2010-09-07 08:06:33,530 DEBUG    Turning the word_count_dict into html
2010-09-07 08:06:33,530 DEBUG    Length word_count_dict: 312
2010-09-07 08:06:33,530 DEBUG    Filtered short words. Length word_count_dict: 176
2010-09-07 08:06:33,530 DEBUG    Filtered blacklist words. Length word_count_dict: 176
2010-09-07 08:06:33,530 DEBUG    Selected most frequent words. Length CloudWords: 42
2010-09-07 08:06:33,530 DEBUG    Min word count: 2, Max word count: 14
2010-09-07 08:06:33,530 DEBUG    Sorted cloud words. Length CloudWords: 42
2010-09-07 08:06:33,530 DEBUG    42 cloud words found
2010-09-07 08:06:33,530 DEBUG    Cloud updated
C:\Program Files\RedNotebook\redNotebook.exe\rednotebook\gui\options.py:339: PangoWarning: Invalid UTF-8 string passed to pango_layout_set_text()
2010-09-07 08:06:49,000 DEBUG    Saving Options
2010-09-07 08:06:49,000 DEBUG    Setting closeToTray = 0
2010-09-07 08:06:49,000 DEBUG    Setting checkForNewVersion = 0
2010-09-07 08:06:49,000 DEBUG    Setting mainFontSize = 12
2010-09-07 08:06:49,000 DEBUG    Setting dateTimeString = %A, %x %X
2010-09-07 08:06:49,000 DEBUG    Setting cloudIgnoreList = 分隔的, 文字, 过滤, 这些, 逗号
2010-09-07 08:06:49,000 DEBUG    Setting cloudIncludeList = mtv, 垃圾邮件, 娱乐, 工作
2010-09-07 08:06:49,000 INFO     Cloud ignore list: ['\xe5\x88\x86\xe9\x9a\x94\xe7\x9a\x84', '\xe6\x96\x87\xe5\xad\x97', '\xe8\xbf\x87\xe6\xbb\xa4', '\xe8\xbf\x99\xe4\xba\x9b', '\xe9\x80\x97\xe5\x8f\xb7']
2010-09-07 08:06:49,000 INFO     Cloud include list: ['mtv', '\xe5\x9e\x83\xe5\x9c\xbe\xe9\x82\xae\xe4\xbb\xb6', '\xe5\xa8\xb1\xe4\xb9\x90', '\xe5\xb7\xa5\xe4\xbd\x9c']
2010-09-07 08:06:49,000 DEBUG    Update the cloud (Type: word, Force: True)
2010-09-07 08:06:49,000 DEBUG    Retrieved WordCountDict. Length: 312
2010-09-07 08:06:49,000 DEBUG    Turning the word_count_dict into html
2010-09-07 08:06:49,000 DEBUG    Length word_count_dict: 312
2010-09-07 08:06:49,000 DEBUG    Filtered short words. Length word_count_dict: 176
2010-09-07 08:06:49,000 DEBUG    Filtered blacklist words. Length word_count_dict: 176
2010-09-07 08:06:49,000 DEBUG    Selected most frequent words. Length CloudWords: 42
2010-09-07 08:06:49,000 DEBUG    Min word count: 2, Max word count: 14
2010-09-07 08:06:49,000 DEBUG    Sorted cloud words. Length CloudWords: 42
2010-09-07 08:06:49,000 DEBUG    42 cloud words found
2010-09-07 08:06:49,000 DEBUG    Cloud updated

**Comment by jendrikseipp** [comment]
*Original comment by* **yanzhisheng** (2010-09-07T00:14:21Z):

----------------------------------------

Hi Jendrik Seipp,
Thank you for your reply. I have post the log file on https://bugs.launchpad.net/rednotebook/+bug/627263
I am looking for your information.
Sincerely,
Zhisheng Yan

--- 10年9月7日，周二, Jendrik Seipp <email address hidden> 写道：


发件人: Jendrik Seipp <email address hidden>
主题: [Bug 627263] Re: export function disabled on windows xp
收件人: <email address hidden>
日期: 2010年9月7日,周二,上午4:45


Thanks for the report.

I cannot replicate the error on my system (win xp sp3). However another
user has reported the same issue by mail and I have redirected him here.
Can you please post your logfile from C:\Documents and
Settings\.rednotebook?

** Changed in: rednotebook
     Assignee: (unassigned) => Jendrik Seipp (jendrikseipp)

** Changed in: rednotebook
     Assignee: Jendrik Seipp (jendrikseipp) => (unassigned)

-- 
export function disabled on windows xp
https://bugs.launchpad.net/bugs/627263
You received this bug notification because you are a direct subscriber
of the bug.

Status in RedNotebook - A Desktop Journal: New

Bug description:
I install RedNotebook 1.1.1 on Windows XP SP2. The Backup works smooth, but when I select the export command, and select the destination and go on from step1 to step5, I have got no exported files. all formats including plain text, html, latex, and pdf are tried, and get on result.
I thought this might be a bug for rednotebook, has anybody else encounter this problem.
I addition, the windows xp is chinese edition.
Thank you in advance.
zhisheng yan

To unsubscribe from this bug, go to:
https://bugs.launchpad.net/rednotebook/+bug/627263/+subscribe

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2010-11-26T18:19:37Z):

----------------------------------------

Do you still get the error with the newest beta? 

http://dl.dropbox.com/u/4780737/rednotebook-1.1.2-b1-win32.exe

**Comment by jendrikseipp** [comment]
*Original comment by* **jhelebrant** (2011-03-22T10:42:28Z):

----------------------------------------

Hi,
I already use the 1.1.3 version and just found that I have almost the same problem - the export process seems to work OK, but there is no result file. I am using it on Windows 7 Professional 64bit. I attached shortened log file.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-03-22T11:44:16Z):

----------------------------------------

Thanks for the log. I think I fixed the issue in trunk. If you know how to checkout a bzr branch you can test it ("bzr branch lp:rednotebook), if not you have to wait for 1.1.4.
