### ISSUE TITLE
Ability to Search for multiple words

### ISSUE THREAD

**Issue by TheBossHoggs** [jendrikseipp/rednotebook#564]
Hi, been really loving and enjoying rednotebook, but i noticed the feature to search for multiple words is absent. not sure if this is already in and i am not seeing it or it is planned for future release.

The ability to search in RedNotebook is one of its greatest features and i think with improving it and adding this ability it will make the program that much stronger

Thanks

**Comment by RJ722** [comment]
We are indeed working on adding support for searching multiple words in #558. In fact, the implementation is almost finalize, so expect a release very soon. \o/

@TheBossHoggs: if you are comfortable with building rednotebook from scratch, it would be great if you can test the code on that PR, and let us know what you think. It will be helpful for us! :)

**Comment by TheBossHoggs** [comment]
Will work on that and let you know! thanks for the quick response. ill post my findings to this thread!

**Comment by TheBossHoggs** [comment]
I tested the code from #558 and it did not work on rednotebook version 2.21.0. i am a bit of a newbie with python so i am not sure if i just messed up syntax but after editing the files that #558 listed. rednotebook would not launch

**Comment by TheBossHoggs** [comment]
Heres an output of my rednotebook log.
2021-03-11 14:27:01,173 INFO     Writing log to file "/root/.rednotebook/rednotebook.log"
2021-03-11 14:27:01,173 INFO     System encoding: utf-8
2021-03-11 14:27:01,173 INFO     Language code: en_US
2021-03-11 14:27:01,301 INFO     Running in portable mode: False
2021-03-11 14:27:01,301 INFO     First Start: False
2021-03-11 14:27:01,301 INFO     RedNotebook version: 2.21
2021-03-11 14:27:01,312 INFO     System info: machine: x86_64, platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.29, processor: x86_64, python_version: 3.8.5, release: 5.4.0-66-generic, system: Linux, GTK: (3, 24, 20), Glib: (2, 64, 2), PyGObject: (3, 36, 0), YAML: 5.3>
2021-03-11 14:27:01,488 DEBUG    Default font: Ubuntu 10
2021-03-11 14:27:01,488 DEBUG    Default size: 10.0
2021-03-11 14:27:01,560 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2021-03-11 14:27:01,560 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
2021-03-11 14:27:01,560 DEBUG    Start compiling regexes
2021-03-11 14:27:01,561 DEBUG    Finished
2021-03-11 14:27:01,586 DEBUG    Tray icon visible: False
2021-03-11 14:27:01,587 INFO     Opening journal at '/root/.rednotebook/data'
2021-03-11 14:27:01,587 DEBUG    Starting to load files in dir "/root/.rednotebook/data"
2021-03-11 14:27:01,587 DEBUG    Finished loading files in dir "/root/.rednotebook/data"
2021-03-11 14:27:01,609 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2021-03-11 14:27:01,609 DEBUG    Start took 0.3077559471130371 seconds
2021-03-11 14:27:01,609 DEBUG    Trying to enter the gtk main loop
2021-03-11 14:27:01,642 DEBUG    Update the cloud
2021-03-11 14:27:01,646 DEBUG    Background color: rgb(64,64,64)
2021-03-11 14:27:01,646 DEBUG    Foreground color: rgb(218,218,218)
2021-03-11 14:27:01,666 DEBUG    Cloud updated
2021-03-11 14:27:01,687 INFO     Last backup was made 0 days ago
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/gui/browser.py", line 86, in on_load_changed
    if self.search_words:
AttributeError: 'Cloud' object has no attribute 'search_words'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_rednotebook_run.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/gui/browser.py", line 86, in on_load_changed
    if self.search_words:
AttributeError: 'Cloud' object has no attribute 'search_words'
2021-03-11 14:27:04,316 DEBUG    Main frame destroyed
2021-03-11 14:27:04,318 INFO     Nothing to save
2021-03-11 14:27:04,319 INFO     Goodbye!
2021-03-11 14:27:04,330 INFO     Peak memory: 134417924 KiB

I know what the errors are, just not sure about going and fixing them any ideas? i just copied the code from #558  and replaced it in my files on my box. 
Thanks

**Comment by TheBossHoggs** [comment]
I followed the add and deletions to files present from "files changed" in #558 and i couldnt get it to work fully, i am going to continue to debug today, but currently having a few issues i believe due to both syntax issues and me being a newbie with python, i am on rednotebook 2.21 and will keep you updated of my findings

**Comment by TheBossHoggs** [comment]
here is an output of the errors i get, any ideas? on how to fix? i can show code if needed
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/gui/browser.py", line 86, in on_load_changed
    if self.search_queries:
AttributeError: 'Cloud' object has no attribute 'search_queries'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_rednotebook_run.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/rednotebook/rednotebook/gui/browser.py", line 86, in on_load_changed
    if self.search_queries:
AttributeError: 'Cloud' object has no attribute 'search_queries'
2021-03-12 07:49:18,848 DEBUG    Main frame destroyed
2021-03-12 07:49:18,850 INFO     Nothing to save
2021-03-12 07:49:18,850 INFO     Goodbye!
2021-03-12 07:49:18,861 INFO     Peak memory: 134417924 KiB

**Comment by RJ722** [comment]
```
File "/usr/share/rednotebook/rednotebook/gui/browser.py", line 86, in on_load_changed
if self.search_queries:
AttributeError: 'Cloud' object has no attribute 'search_queries'
```

Ha, that looks like an old version in the same PR.

> I followed the add and deletions to files present from "files changed" in #558

I suspect that a commit got lost somewhere, or that the changes weren't applied cleanly. Can you maybe try checking out the branch using git:

```
git clone https://github.com/jendrikseipp/rednotebook/
cd rednotebook/
git fetch origin new-search
git checkout new-search
```

If you don't want to use git, try applying [this patch](https://patch-diff.githubusercontent.com/raw/jendrikseipp/rednotebook/pull/558.diff) on latest rednotebook. Something like the following should work I suppose:

```
cd rednotebook
curl https://patch-diff.githubusercontent.com/raw/jendrikseipp/rednotebook/pull/558.diff | patch -p1 --verbose
```
---

Regarding the other import error, I am assuming that there was a problem during installation. Did you follow instructions from https://github.com/jendrikseipp/rednotebook/#install-on-linux? Note that you'd need all the [requiremenets](https://github.com/jendrikseipp/rednotebook/#requirements) as well.
