### ISSUE TITLE
RedNotebook 2.21 fails to start due to errors

### ISSUE THREAD

**Issue by ElnuDev** [jendrikseipp/rednotebook#570]
**To Reproduce**

1. Download RedNotebook 2.21 source code
2. Unzip source code
3. Open unzipped source code folder in terminal
4. `pip3 install .`
5. `rednotebook`

The following errors will output:

```
Traceback (most recent call last):
  File "/home/elnu/.local/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elnu/.local/bin/rednotebook", line 12, in <module>
    import rednotebook.journal
  File "/home/elnu/.local/lib/python3.8/site-packages/rednotebook/journal.py", line 45, in <module>
    gi.require_version("GtkSource", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 3.0
```

**Versions:**
- RedNotebook version 2.21
- Operating system and version: Pop!_OS 20.10

**Comment by jendrikseipp** [comment]
You'll need to install the package gir1.2-gtksource-3.0 first. If that doesn't help, try the PPA at https://code.launchpad.net/~rednotebook/+archive/ubuntu/stable.

**Comment by ElnuDev** [comment]
That fixed the issue! Thank you so much, I really appreciate it.
