### ISSUE TITLE
Google Drive for Desktop "The Journal could not be saved"

### ISSUE THREAD

**Issue by iesoftwaredeveloper** [jendrikseipp/rednotebook#593]
**Describe the bug**
I recently updated my local google drive client from Backup and Sync to "Google Drive for Desktop"  After the upgrade any attempt to open and save a journal results in the message "The Journal could not be saved".

My best guess is that the drive is seen by Python or Rednotebook as a network drive and it seems the same issue occurs with network drives.

If I try to open the journal file in something like notepad I have no errors saving the file.  So it seems to be specific to rednotebook and how it is attempting to write to the existing file.

Rednotebook will create two new files on the google drive.  So while it can't save the existing file, it does not appear to be a permissions issue on the directory itself.

The new files created are the same name as the current file but with "new" and "old" added in.  As you would expect, the new is the current version in Rednotebook and old is the original file.

Prior to the Google Drive for Desktop update it was working fine.  This leads me to the hypothesis that the way that the directory is seen by Rednotebook is different that it was previously.  

The Google Drive folder changed from just another sub directory on my local drive to a mapped "G:" drive.

I have tried to fix by creating a sub directory that is a link to the G drive in hopes that I could trick the system into treating the directory as a standard directory, but that resulted in the same behavior.

**To Reproduce**
1. Install Google Drive for Desktop onto your Windows machine
2. Create a folder to hold your journal
3. Open Rednotebook and open your the journal directory.
4. Make a change to the current journal day.
5. Save the journal.
6. See dialog box appear.

**Expected behavior**
When saving to a local copy of the file I expect it to just save to the existing journal file that was opened.

**Screenshots**
No screen shots.

**Versions:**
Rednotebook version: 2.22 for Windows.
Running windows version: Windows 10 Education 20H2 19042.1165
Google Drive for Deskop: 50.0.11.0

**Log output when reproducing bug**
2021-08-23 09:49:04,111 DEBUG    Loading file "C:\Users\xxxxxxx\Documents\rednotebook\data\2021-08.txt"
2021-08-23 09:49:04,116 DEBUG    Finished loading files in dir "C:\Users\xxxxxxx\Documents\rednotebook\data"
2021-08-23 09:49:04,495 INFO     Connected Signals: [2, 22, 15]
2021-08-23 09:49:04,495 DEBUG    Start took 2.205422878265381 seconds
2021-08-23 09:49:04,495 DEBUG    Trying to enter the gtk main loop
2021-08-23 09:49:04,634 INFO     Last backup was made 5 days ago
2021-08-23 09:49:12,033 ERROR    Saving month files failed: 'C:\\Users\\xxxxxxx\\Documents\\rednotebook\\data\\2021-08.txt' and 'C:\\Users\\xxxxxxx\\Documents\\rednotebook\\data\\2021-08.old.txt' are the same file
2021-08-23 09:49:13,622 INFO     The journal could not be saved

**Comment by iesoftwaredeveloper** [comment]
After writing a simple test python script, I was able to replicate what might be the error. 

In the first iteration of the script, all works as expected.  In a slightly different version it fails after the third attempt.

For the first version of the script I get the following results:

1. Execute script
2. new.txt is created
2. new.txt is moved to filename.txt
3. Execute the script again.
4. new.txt is created.
5. old.txt is created.
6. new.txt is moved to filename.txt
7. new.txt remains.
8. Run script third time and all of the steps from iteration 2 repeat and work as expected.

If I run the second version of the script where I do not remove the old.txt file it will cause an error.  Here are the step to replicate.

1. execute script
2. new.txt is created.
3. new.txt is moved to filename.txt
4. Execute script for second time.
5. new.txt is created.
6. filename.txt is copied to old.txt
7. new.txt is moved to filename.txt
8. old.txt is NOT removed since that code is commented out.
9. Execute the script a third time.
10.  new.txt is created.
11. Attempt to copy filename.txt to old.txt is made, but fails.

When viewing the journal files when the error occurs in RedNotebook, I see that there is the new, old and original file.  For this reason, I suspect that the error I get in my test scenario is similar to what is occurring when using RedNotebook.

The error that I get when attempting to move the original file to old.txt when old.txt still exists is the following:

```
Traceback (most recent call last):
  File "/mnt/c/tmp/testmv.py", line 28, in <module>
    demo_move_file()
  File "/mnt/c/tmp/testmv.py", line 21, in demo_move_file
    shutil.copy2(filename, old)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'filename.txt' and 'old.txt' are the same file
```

I suspect that when RedNotebook attempts to do the file moves that the removal of old.txt fails.  Subsequent attempts to copy the journal file results in an error similar to above.  Since I can't see what the actual error is from RedNotebook, this is just speculation.

Provided old.txt exists, both versions of the test script fail.  Since I can see 2021-08.old.txt, I believe this is where the failure is occurring.

Here are the test script files I used to try an replicate the error.

Test script 1 (which works and does not cause any errors, provide old.txt does not exist)
```
import codecs
import os
import shutil
import yaml
from yaml import Dumper

def demo_move_file():
    old = "old.txt"
    new = "new.txt"
    filename = "filename.txt"

    with codecs.open(new, "wb", encoding="utf-8") as f:
        #f.write("some content")
        yaml.dump("somecontent: 'yes'", f, Dumper=Dumper, allow_unicode=True)

    if os.path.exists(filename):
        shutil.copy2(filename, old)
    shutil.move(new, filename)
    if os.path.exists(old):
        os.remove(old)



demo_move_file()
```

And the same script slightly modified to ensure that old.txt is not removed.  This results in the errors above.  I can produce the same error in both versions of the script by simply ensuring that old.txt exists before running the script.

```
import codecs
import os
import shutil
import yaml
from yaml import Dumper

def demo_move_file():
    old = "old.txt"
    new = "new.txt"
    filename = "filename.txt"

    with codecs.open(new, "wb", encoding="utf-8") as f:
        #f.write("some content")
        yaml.dump("somecontent: 'yes'", f, Dumper=Dumper, allow_unicode=True)

    if os.path.exists(filename):
        shutil.copy2(filename, old)
    shutil.move(new, filename)
    #if os.path.exists(old):
    #    os.remove(old)



demo_move_file()
```

**Comment by jendrikseipp** [comment]
Thanks for the detailed report! Do you think you could work on a fix for this and prepare a pull request?

**Comment by iesoftwaredeveloper** [comment]
Python is not something I am fluent it.  I will continue to see what I can do.  If I find a solution I will certainly prepare a pull request.

**Comment by jendrikseipp** [comment]
Awesome!

**Comment by iesoftwaredeveloper** [comment]
I have not been able to compile the source on my local environment to verify my change.  However, I can simulate the change.  It seems that if you do the following it will work.  I simulated this by manually removing the file before saving.

To replicate do the following:
1. Ensure a year-month.txt file exists on the google drive for desktop location on the local host.
2. Make a change to the journal entry.
3. Attempt to save.
4. Verify that error message appears.
5. Verify that year-month.new.txt, year-month.old.txt and year-month.txt exists.
6. Verify that year-month.txt and year-month.old.txt are the same contents.  year-month.new.txt contains the latest entires.
7. No manually delete the year-month.txt file.
8. Attempt to save the current journal entry.
9. Verify that a new year-month.txt file is created.
10. Verify that the year-month.new.txt and year-month.old.txt files are removed.

When did this with the current version 2.22 it worked.  This lead me to believe that if you slightly modify the storage.py file to do the following it will resolve the issue.   I suspect this is a timing thing.  The google drive for desktop likely has a lock on the file that just prevents things from occurring effectively and that link to the existing file needs to be avoided to avoid the lock.

Modify the source from the current:
```python
    if os.path.exists(filename):
        mtime = os.path.getmtime(filename)
        if mtime != month.mtime:
            conflict = get_filename(".CONFLICT_BACKUP" + str(mtime))
            logging.debug(
                "Last edit time of %s conflicts with edit time at file load\n"
                "--> Backing up to %s" % (filename, conflict)
            )
            shutil.copy2(filename, conflict)
        shutil.copy2(filename, old)
    shutil.move(new, filename)
    if os.path.exists(old):
        os.remove(old)
```

And add a quick remove of the current year-month.txt file as follows:
```python
    if os.path.exists(filename):
        mtime = os.path.getmtime(filename)
        if mtime != month.mtime:
            conflict = get_filename(".CONFLICT_BACKUP" + str(mtime))
            logging.debug(
                "Last edit time of %s conflicts with edit time at file load\n"
                "--> Backing up to %s" % (filename, conflict)
            )
            shutil.copy2(filename, conflict)
        shutil.copy2(filename, old)
    if os.path.exists(filename): # <=== ADDED TO REMOVE THE FILE TO AVOID MOVE ISSUES
        os.remove(filename) # <=== REMOVE CURRENT FILE BEFORE MOVING NEW TO CURRENT
    shutil.move(new, filename)
    if os.path.exists(old):
        os.remove(old)
```

Unfortunately since I can't get it to compile in my local environment I am unable to validate the actual code change and must rely on the results of my testing of version 2.22 behavior.

Hopefully someone will see this issue and can test.  I do not want to open a PR until it has been verified locally.

**Comment by jendrikseipp** [comment]
Thanks! I'll look into this more closely when I find the time.

**Comment by iesoftwaredeveloper** [comment]
I was finally able to resolve my local issues.  I was having issues getting the gtk+ installed.  Now that I have been able to get my environment working I was able to test my solution.  It worked.  I suspect that because the new version of Google Drive for Desktop is now streaming everything by default instead of downloading local copies that the year-month.txt file is somehow locked while it is performing the updates to the cloud.  This is locked just long enough to cause the move of the year-month.new.txt file to fail.

I will submit a PR request for review now that I have been able to test and verify the work-around.
