### ISSUE TITLE
rednotebook fails to start on fedora rawhide

### ISSUE THREAD

**Issue by kathenas** [jendrikseipp/rednotebook#634]
Error below.

Adding /usr/lib/python3.11/site-packages to sys.path
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    import rednotebook.journal
  File "/usr/lib/python3.11/site-packages/rednotebook/journal.py", line 100, in <module>
    elibintl.install(GETTEXT_DOMAIN, LOCALE_PATH, libintl=None)
  File "/usr/lib/python3.11/site-packages/rednotebook/external/elibintl.py", line 472, in install
    _install(domain, localedir, True, libintl=libintl)
  File "/usr/lib/python3.11/site-packages/rednotebook/external/elibintl.py", line 431, in _install
    gettext.bind_textdomain_codeset(domain, 'UTF-8')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'

**Comment by jendrikseipp** [comment]
Thanks for the report! I think this is fixed in version 2.26 that I just released. Can you confirm?

**Comment by kathenas** [comment]
Confirmed. This fixes the issue on fedora rawhide. I will do releases for fedora and debian during today.

**Comment by jendrikseipp** [comment]
Great!
