### ISSUE TITLE
RN running only in background

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#64]
I installed the new version (1.2) yesterday and since then I have the problem, that it looks like RN is running in the background and I can't see it or stop it. When I try to open it I get the following message:

RedNotebook scheint bereits zu laufen
Das kann passieren, wenn sich die Anwendung im Systembereich verbirgt oder sie nicht korrekt beendet wurde. Wenn eine zweite Instanz von RedNotebook gestartet wird, kann das zu Datenverlusten führen. Bitte prüfe deshalb, ob die Anwendung nicht schon läuft.

Soll trotzdem eine neue Instanz von RedNotebook gestartet werden?

To delete the "running" line in the conf-file doesn't help! Also it is not located in the sys-tray.

Here are my conf and log files:

log:
2011-10-10 11:10:11,497 DEBUG    sys.stdout logging level: 20
2011-10-10 11:10:11,499 INFO     Writing log to file "/home/charly/.rednotebook/rednotebook.log"
2011-10-10 11:10:12,139 WARNING  RedNotebook instance already running

conf:
checkForNewVersion=1
closeToTray=0
cloudIgnoreList=*, *, abgest, ausführ*, bereich, die, doch, durch, einer, erfolgt, eventuell, ist, kein, keine, kommt, möglich, nicht, nur, offen, seitens, vorgesehen, weitere, werden, wurde
cloudIncludeList=job, juli, mtv, spam
cloudTabActive=1
dataDir=/media/Kingston/Firma/Notizen_Frima
dateTimeString=%A, %x %X
exportDateFormat=%A, %x
firstStart=0
leftDividerPosition=236
mainFontSize=-1
mainFrameHeight=576
mainFrameMaximized=1
mainFrameWidth=1024
mainFrameX=0
mainFrameY=24
rightDividerPosition=540
running=1
spellcheck=1
userDir=
weekNumbers=1

I hope you find a quick solution, because I use RN on daily basis in my work and can't do anything with it now!! 
Is there a way to install the old version (1.1.8)?

charly

**Comment by jendrikseipp** [comment]
*Original comment by* **charlymr** (2011-10-10T10:54:24Z):

----------------------------------------

I forgot to say, that I work with Ubuntu 11.04

charly

**Comment by jendrikseipp** [comment]
*Original comment by* **charlymr** (2011-10-10T12:16:44Z):

----------------------------------------

Here's another log, after I tried to start it again:

2011-10-10 14:14:04,167 DEBUG    sys.stdout logging level: 20
2011-10-10 14:14:04,167 INFO     Writing log to file "/home/charly/.rednotebook/rednotebook.log"
2011-10-10 14:14:05,769 WARNING  RedNotebook instance already running
2011-10-10 14:14:15,436 INFO     Running in portable mode: False
2011-10-10 14:14:15,437 INFO     First Start: False
2011-10-10 14:14:15,437 INFO     RedNotebook version: 1.2.0
2011-10-10 14:14:15,469 INFO     System info: machine: i686, platform: Linux-2.6.38-11-generic-i686-with-Ubuntu-11.04-natty, processor: i686, python_version: 2.7.1+, release: 2.6.38-11-generic, system: Linux, GTK version: (2, 24, 4), PyGTK version: (2, 22, 0), Yaml version: 3.09
2011-10-10 14:14:16,358 DEBUG    Default font: Ubuntu 11
2011-10-10 14:14:16,358 DEBUG    Default size: 11
2011-10-10 14:14:17,032 INFO     Cloud ignore list: [u'*', u'*', u'abgest', u'ausf\xfchr*', u'bereich', u'die', u'doch', u'durch', u'einer', u'erfolgt', u'eventuell', u'ist', u'kein', u'keine', u'kommt', u'm\xf6glich', u'nicht', u'nur', u'offen', u'seitens', u'vorgesehen', u'weitere', u'werden', u'wurde']
2011-10-10 14:14:17,033 INFO     Cloud include list: [u'job', u'juli', u'mtv', u'spam']
2011-10-10 14:14:17,033 DEBUG    Start compiling regexes
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.journal.main()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 664, in main
    journal = Journal()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 251, in __init__
    self.frame = MainWindow(self)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-10-10T16:50:53Z):

----------------------------------------

The log seems to be truncated, is it complete?

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-10-10T17:49:13Z):

----------------------------------------

The current behaviour works as follows:

Read the config file. If running = 1 show warning. Write running = 1 to the config file. Before program shutdown, write running = 0.

Does that give you a hint about the bug's source?

**Comment by jendrikseipp** [comment]
*Original comment by* **charlymr** (2011-10-10T20:28:51Z):

----------------------------------------

It's the whole log - the first without trying to restart and the second after I tried to restart.

In my confg-file running is always on 1

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-10-10T20:39:40Z):

----------------------------------------

ok, thanks. Can you please try the following steps:

- open the config file
- delete the line "running = "
- save the config file (this is important)
- start RedNotebook from the commandline
- click "start nevertheless" if the dialog appears
- paste the output here

**Comment by jendrikseipp** [comment]
*Original comment by* **charlymr** (2011-10-11T04:41:23Z):

----------------------------------------

OK, I did as you wrote, but nothing happend (no dialog, no RN open). Here is the output:

-----------------------------------------------------------------------------------------------------

charly@charly-S310:~$ rednotebook
INFO     Writing log to file "/home/charly/.rednotebook/rednotebook.log"
INFO     Configuration has been saved to /home/charly/.rednotebook/configuration.cfg
INFO     Running in portable mode: False
INFO     First Start: False
INFO     RedNotebook version: 1.2.0
INFO     System info: machine: i686, platform: Linux-2.6.38-11-generic-i686-with-Ubuntu-11.04-natty, processor: i686, python_version: 2.7.1+, release: 2.6.38-11-generic, system: Linux, GTK version: (2, 24, 4), PyGTK version: (2, 22, 0), Yaml version: 3.09
INFO     Cloud ignore list: [u'*', u'*', u'abgest', u'ausf\xfchr*', u'bereich', u'die', u'doch', u'durch', u'einer', u'erfolgt', u'eventuell', u'ist', u'kein', u'keine', u'kommt', u'm\xf6glich', u'nicht', u'nur', u'offen', u'seitens', u'vorgesehen', u'weitere', u'werden', u'wurde']
INFO     Cloud include list: [u'job', u'juli', u'mtv', u'spam']
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.journal.main()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 664, in main
    journal = Journal()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 251, in __init__
    self.frame = MainWindow(self)
  File "/usr/share/rednotebook/rednotebook/gui/main_window.py", line 170, in __init__
    self.setup_clouds()
  File "/usr/share/rednotebook/rednotebook/gui/main_window.py", line 427, in setup_clouds
    self.cloud = Cloud(self.journal)
  File "/usr/share/rednotebook/rednotebook/gui/clouds.py", line 113, in __init__
    self.update_lists()
  File "/usr/share/rednotebook/rednotebook/gui/clouds.py", line 140, in update_lists
    self.update_regexes()
  File "/usr/share/rednotebook/rednotebook/gui/clouds.py", line 144, in update_regexes
    self.regexes_ignore = [get_regex(word) for word in self.ignore_list]
  File "/usr/share/rednotebook/rednotebook/gui/clouds.py", line 48, in get_regex
    return re.compile(word + '$', re.I)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
charly@charly-S310:~$

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-10-11T19:50:19Z):

----------------------------------------

Thanks, the problem is that "*" is no valid regular expression. If you 
want to hide all words, the regex must be ".*"

I added some error handling in trunk, too.

**Comment by jendrikseipp** [comment]
*Original comment by* **charlymr** (2011-10-12T04:40:17Z):

----------------------------------------

Thanks!!! Works fine again now!

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-01-24T18:42:58Z):

----------------------------------------

Fixed in version 1.3
