### ISSUE TITLE
2.29.4 fails to load existing data

### ISSUE THREAD

**Issue by stevenbrown2** [jendrikseipp/rednotebook#686]
**Describe the bug**
Installed latest release 2.29.4.  upon completion loaded application, no data present.  Tried to open existing c:\users\username\.rednotebook\data. still no data displayed

**To Reproduce**
1. Shut down current version 2.29.3
2. download and install 2.29.4
3. launch new version
4. no existing data shown
5. tried to open existing .rednotebook/data directory
6. it completes the open but still no existing data dispalyed

**Expected behavior**
As with previous updates, upon launching new version, existing data is displayed.

**Screenshots**

**Versions:**
- RedNotebook version upgrading from 2.29.3 to 2.29.4
- Operating system and version: Windows 11 22H2 22621.1413

**Log output when reproducing bug**
2023-04-12 10:12:51,804 INFO     Writing log to file "C:\Users\steven.brown\.rednotebook\rednotebook.log"
2023-04-12 10:12:51,804 INFO     System encoding: utf-8
2023-04-12 10:12:51,805 INFO     Language code: en_US
2023-04-12 10:12:51,846 WARNING  For spell checking, please install enchant (python3-enchant).
2023-04-12 10:12:51,883 WARNING  WebKit2 4.1 not found. Trying to use arbitrary version. Error message: 'Namespace WebKit2 not available'
2023-04-12 10:12:51,906 INFO     Using LibYAML
2023-04-12 10:12:51,907 INFO     Connected Signals: [<Signals.SIGINT: 2>, <Signals.SIGABRT: 22>, <Signals.SIGTERM: 15>]
2023-04-12 10:12:52,037 INFO     Running in portable mode: False
2023-04-12 10:12:52,037 INFO     First Start: False
2023-04-12 10:12:52,037 INFO     RedNotebook version: 2.29.4
Traceback (most recent call last):
  File "rednotebook\journal.py", line 236, in do_startup
  File "rednotebook\util\filesystem.py", line 209, in get_platform_info
  File "gi\importer.py", line 131, in load_module
ImportError: cannot import name WebKit2, introspection typelib not found
2023-04-12 10:12:52,695 DEBUG    Default font: Segoe UI 9
2023-04-12 10:12:52,695 DEBUG    Default size: 9.0
2023-04-12 10:12:53,030 DEBUG    Tray icon visible: True
2023-04-12 10:13:02,009 DEBUG    2021-12.CONFLICT_BACKUP1640200839.2727518.txt is not a valid month filename
2023-04-12 10:13:02,009 DEBUG    2022-06.CONFLICT_BACKUP1655206065.1761706.txt is not a valid month filename
2023-04-12 10:13:02,010 INFO     Opening journal at 'C:\\Users\\steven.brown\\.rednotebook\\data'
2023-04-12 10:13:02,010 DEBUG    Starting to load files in dir "C:\Users\steven.brown\.rednotebook\data"
2023-04-12 10:13:02,010 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-03.txt"
2023-04-12 10:13:02,011 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-04.txt"
2023-04-12 10:13:02,012 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-05.txt"
2023-04-12 10:13:02,013 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-06.txt"
2023-04-12 10:13:02,014 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-07.txt"
2023-04-12 10:13:02,016 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-08.txt"
2023-04-12 10:13:02,017 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-09.txt"
2023-04-12 10:13:02,018 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-10.txt"
2023-04-12 10:13:02,019 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-11.txt"
2023-04-12 10:13:02,021 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2019-12.txt"
2023-04-12 10:13:02,022 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-01.txt"
2023-04-12 10:13:02,023 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-02.txt"
2023-04-12 10:13:02,025 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-03.txt"
2023-04-12 10:13:02,025 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-04.txt"
2023-04-12 10:13:02,026 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-05.txt"
2023-04-12 10:13:02,027 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-06.txt"
2023-04-12 10:13:02,029 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-07.txt"
2023-04-12 10:13:02,031 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-08.txt"
2023-04-12 10:13:02,032 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-09.txt"
2023-04-12 10:13:02,033 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-10.txt"
2023-04-12 10:13:02,034 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-11.txt"
2023-04-12 10:13:02,036 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2020-12.txt"
2023-04-12 10:13:02,037 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-01.txt"
2023-04-12 10:13:02,039 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-02.txt"
2023-04-12 10:13:02,040 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-03.txt"
2023-04-12 10:13:02,042 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-04.txt"
2023-04-12 10:13:02,043 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-05.txt"
2023-04-12 10:13:02,045 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-06.txt"
2023-04-12 10:13:02,046 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-07.txt"
2023-04-12 10:13:02,047 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-08.txt"
2023-04-12 10:13:02,049 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-09.txt"
2023-04-12 10:13:02,050 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-10.txt"
2023-04-12 10:13:02,051 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-11.txt"
2023-04-12 10:13:02,052 DEBUG    2021-12.CONFLICT_BACKUP1640200839.2727518.txt is not a valid month filename
2023-04-12 10:13:02,052 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2021-12.txt"
2023-04-12 10:13:02,055 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-01.txt"
2023-04-12 10:13:02,056 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-02.txt"
2023-04-12 10:13:02,057 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-03.txt"
2023-04-12 10:13:02,059 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-04.txt"
2023-04-12 10:13:02,060 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-05.txt"
2023-04-12 10:13:02,061 DEBUG    2022-06.CONFLICT_BACKUP1655206065.1761706.txt is not a valid month filename
2023-04-12 10:13:02,061 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-06.txt"
2023-04-12 10:13:02,063 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-07.txt"
2023-04-12 10:13:02,064 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-08.txt"
2023-04-12 10:13:02,065 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-09.txt"
2023-04-12 10:13:02,067 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-10.txt"
2023-04-12 10:13:02,068 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-11.txt"
2023-04-12 10:13:02,070 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2022-12.txt"
2023-04-12 10:13:02,072 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-01.txt"
2023-04-12 10:13:02,073 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-02.txt"
2023-04-12 10:13:02,075 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-03.txt"
2023-04-12 10:13:02,076 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-04.txt"
2023-04-12 10:13:02,076 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-05.txt"
2023-04-12 10:13:02,076 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-06.txt"
2023-04-12 10:13:02,077 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-07.txt"
2023-04-12 10:13:02,077 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-08.txt"
2023-04-12 10:13:02,077 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-09.txt"
2023-04-12 10:13:02,077 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-10.txt"
2023-04-12 10:13:02,078 DEBUG    Loading file "C:\Users\steven.brown\.rednotebook\data\2023-11.txt"
2023-04-12 10:13:02,078 DEBUG    Finished loading files in dir "C:\Users\steven.brown\.rednotebook\data"
Traceback (most recent call last):
  File "rednotebook\gui\menu.py", line 331, in on_open_journal_button_activate
  File "rednotebook\gui\menu.py", line 319, in select_journal
  File "rednotebook\journal.py", line 419, in open_journal
AttributeError: 'Journal' object has no attribute 'actual_date'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 539, in on_back_one_day_button_clicked
  File "rednotebook\journal.py", line 519, in go_to_prev_day
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 539, in on_back_one_day_button_clicked
  File "rednotebook\journal.py", line 519, in go_to_prev_day
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 539, in on_back_one_day_button_clicked
  File "rednotebook\journal.py", line 519, in go_to_prev_day
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.timedelta'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 959, in on_day_selected
  File "rednotebook\journal.py", line 508, in change_date
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'
Traceback (most recent call last):
  File "rednotebook\gui\main_window.py", line 380, in on_quit_activate
  File "rednotebook\journal.py", line 335, in exit
  File "rednotebook\journal.py", line 358, in save_to_disk
  File "rednotebook\journal.py", line 472, in save_old_day
  File "rednotebook\journal.py", line 496, in day
AttributeError: 'NoneType' object has no attribute 'get_day'

**Comment by jendrikseipp** [comment]
Thanks for the report! This is now fixed in version 2.29.5.
