### ISSUE TITLE
Exception on first run when .rednotebook exists (from backup)

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#69]
Hi,

When I restore my backup, and make a symbolic link in /home/jorg/.rednotenook to /data/AppData/rednotebook (I keep config seperate), on the first run with rednotebook 1.2.0 in FC16, I get this exception:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 11, in <module>
    import rednotebook.journal
  File "/usr/lib/python2.7/site-packages/rednotebook/journal.py", line 164, in <module>
    dirs = filesystem.Filenames(default_config)
  File "/usr/lib/python2.7/site-packages/rednotebook/util/filesystem.py", line 92, in __init__
    self.temp_dir])
  File "/usr/lib/python2.7/site-packages/rednotebook/util/filesystem.py", line 191, in make_directories
    make_directory(dir)
  File "/usr/lib/python2.7/site-packages/rednotebook/util/filesystem.py", line 187, in make_directory
    os.makedirs(dir)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/jorg/.rednotebook'

And the first run should be not putting stuff in an existing diary. That bug existed for some time, where an existing dir gets "example" entries on it.

Thanks,
- Jorgen

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-12-21T20:38:31Z):

----------------------------------------

I looked at your scenario and I think this error can only happen if that
symlink is broken in which case there should be an error.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2011-12-21T20:43:27Z):

----------------------------------------

Concerning the instructions: I added a second check before adding them.
If the same error comes up in version 1.3 please report the log output
and your configuration here.

**Comment by jendrikseipp** [comment]
*Original comment by* **jorgb** (2011-12-21T21:10:33Z):

----------------------------------------

Hi,

I believe the symlink was valid, but I will check the next time for
sure. It just said that the directory already existed. But in any case,
please fix the "initial run" bug where when RedNotebook is started for
the first time in an _already filled_ diary folder, it fills today,
tomorrow and the next day with example data. I assume that is simple to
check if there are data files in there, skip the example generation, or
at least ask in the beginning. Even long-time RedNotebook users will
start to find that annoying, that making a new empty diary folder does
not necessesarily has to be filled again with the example data as they
already know how to use the software. 

Thanks,
- Jorgen

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-01-20T13:45:27Z):

----------------------------------------

These errors should be gone in (unreleased) version 1.3.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-01-24T22:30:24Z):

----------------------------------------

Fixed in version 1.3
