### ISSUE TITLE
App won't launch on Linux

### ISSUE THREAD

**Issue by undeadbydawn** [jendrikseipp/rednotebook#693]
Running 2.29.6-1 on Arch Linux kernel 6.3.1, KDE
Clicking the app icon to launch fails, so doing 'rednotebook' in Terminal to get feedback

```
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    import rednotebook.journal
ModuleNotFoundError: No module named 'rednotebook'
```

**Comment by undeadbydawn** [comment]
Ok, just ran a system update and now getting this glorious pile of errors

```
INFO     Using GtkSourceView 4
Adding /usr/lib/python3.11/site-packages to sys.path
INFO     Available versions of the WebKit2 namespace: ['4.0', '4.1']
INFO     Loaded version of the WebKit2 namespace: 4.1
INFO     Locale path: /usr/share/locale
2023-05-04 10:20:48,145 INFO     Writing log to file "/home/vasya/.rednotebook/rednotebook.log"
2023-05-04 10:20:48,146 INFO     System encoding: utf-8
2023-05-04 10:20:48,146 INFO     Language code: en_GB

** (rednotebook:18012): WARNING **: 10:20:48.151: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (rednotebook:18012): WARNING **: 10:20:48.151: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (rednotebook:18012): WARNING **: 10:20:48.151: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

2023-05-04 10:20:48,151 INFO     Spell checking languages: ['en', 'en_AU', 'en_CA', 'en_GB', 'en_US']
2023-05-04 10:20:48,151 INFO     Spell checking dictionaries: [('en', <Enchant: Aspell Provider>), ('en_AU', <Enchant: Aspell Provider>), ('en_CA', <Enchant: Aspell Provider>), ('en_GB', <Enchant: Aspell Provider>), ('en_US', <Enchant: Aspell Provider>)]

(rednotebook:18012): Gtk-WARNING **: 10:20:48.169: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(rednotebook:18012): Gtk-WARNING **: 10:20:48.169: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
2023-05-04 10:20:48,227 INFO     Using LibYAML
2023-05-04 10:20:48,228 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2023-05-04 10:20:48,229 INFO     Running in portable mode: False
2023-05-04 10:20:48,230 INFO     First Start: False
2023-05-04 10:20:48,230 INFO     RedNotebook version: 2.29.6
2023-05-04 10:20:48,230 INFO     System info: machine: x86_64, platform: Linux-6.3.1-1-cachyos-bore-x86_64-with-glibc2.37, processor: , python_version: 3.11.3, release: 6.3.1-1-cachyos-bore, system: Linux, GTK: (3, 24, 37), Glib: (2, 76, 1), PyGObject: (3, 44, 1), YAML: 6.0, WebKit2: (2, 40, 1)
2023-05-04 10:20:48,447 DEBUG    Default font: Quicksand Medium 10
2023-05-04 10:20:48,447 DEBUG    Default size: 10.0

** (rednotebook:18012): WARNING **: 10:20:48.447: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (rednotebook:18012): WARNING **: 10:20:48.448: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (rednotebook:18012): WARNING **: 10:20:48.448: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

2023-05-04 10:20:48,504 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2023-05-04 10:20:48,504 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
2023-05-04 10:20:48,504 DEBUG    Start compiling regexes
2023-05-04 10:20:48,504 DEBUG    Finished
2023-05-04 10:20:48,508 DEBUG    Tray icon visible: False

(rednotebook:18012): Gtk-CRITICAL **: 10:20:48.508: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
2023-05-04 10:20:48,512 INFO     Opening journal at '/home/vasya/.rednotebook/data'
2023-05-04 10:20:48,512 DEBUG    Starting to load files in dir "/home/vasya/.rednotebook/data"
2023-05-04 10:20:48,512 DEBUG    Loading file "/home/vasya/.rednotebook/data/2022-12.txt"
2023-05-04 10:20:48,514 DEBUG    Loading file "/home/vasya/.rednotebook/data/2023-01.txt"
2023-05-04 10:20:48,515 DEBUG    Loading file "/home/vasya/.rednotebook/data/2023-02.txt"
2023-05-04 10:20:48,515 DEBUG    Loading file "/home/vasya/.rednotebook/data/2023-03.txt"
2023-05-04 10:20:48,516 DEBUG    Loading file "/home/vasya/.rednotebook/data/2023-04.txt"
2023-05-04 10:20:48,517 DEBUG    Loading file "/home/vasya/.rednotebook/data/2023-05.txt"
2023-05-04 10:20:48,517 ERROR    Error in file /home/vasya/.rednotebook/data/2023-05.txt:
while parsing a block mapping
  in "/home/vasya/.rednotebook/data/2023-05.txt", line 147, column 3
did not find expected key
  in "/home/vasya/.rednotebook/data/2023-05.txt", line 157, column 56
```
