### ISSUE TITLE
link to 'thunderlink://xxxx ' fails on windows 

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#72]
using RN 1.3 - inserting a link i. e.:
 [myLink  ""thunderlink://<email address hidden>""]
into RN is accepted and displayed correctly.

Clicking this link will result in this log:
INFO     Clicked URI "thunderlink://messageid%<email address hidden>"
DEBUG    Transformed local URI thunderlink://messageid%<email address hidden> to file:///thunderlink:\<email address hidden>
INFO     Trying to open file:///thunderlink:\<email address hidden> with "os.startfile"
ERROR    Opening file:///thunderlink:\<email address hidden> with "os.startfile" failed
Traceback (most recent call last):
  File "rednotebook\util\filesystem.pyc", line 318, in open_url
WindowsError: [Error 3] Das System kann den angegebenen Pfad nicht finden: u'file:///thunderlink:\\<email address hidden>'
INFO     Trying to open file:///thunderlink:\<email address hidden> with webbrowser
sageid%<email address hidden> to file:///thunderlink:\<email address hidden>
2012-01-25 15:34:11,483 INFO     Trying to open file:///thunderlink:\<email address hidden> with "os.startfile"
2012-01-25 15:34:11,515 ERROR    Opening file:///thunderlink:\<email address hidden> with "os.startfile" failed
Traceback (most recent call last):
  File "rednotebook\util\filesystem.pyc", line 318, in open_url
WindowsError: [Error 3] Das System kann den angegebenen Pfad nicht finden: u'file:///thunderlink:\\<email address hidden>'
2012-01-25 15:34:11,515 INFO     Trying to open file:///thunderlink:\<email address hidden> with webbrowser

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-01-25T14:57:53Z):

----------------------------------------

Thanks for the report. I have never seen "thunderlink" before. You can
add normal mails by using

[myLink  ""mailto:<email address hidden>""]

Does it work under windows?

Alternatively you can export your content and see if opening the links
in a browser works. Does it?

**Comment by jendrikseipp** [comment]
*Original comment by* **bau-x** (2012-01-26T11:06:18Z):

----------------------------------------

Trying [myLink  ""mailto:<email address hidden>""] results 
in the same log-output (see below)

The problem is, that a url is always transformed in this way:
'protocol://url' --> 'file:///protocol://url'!
only if protocol==http the link is left untouched.

I looked into the source and saw that 'get_local_url' is doing this.

2012-01-26 11:57:10,812 INFO     Clicked URI 
"mailto:<email address hidden>"
2012-01-26 11:57:10,812 DEBUG    Transformed local URI 
mailto:<email address hidden> to 
file:///mailto:<email address hidden>
2012-01-26 11:57:10,812 INFO     Trying to open 
file:///mailto:<email address hidden> with "os.startfile"
2012-01-26 11:57:10,858 ERROR    Opening 
file:///mailto:<email address hidden> with "os.startfile" failed
Traceback (most recent call last):
   File "rednotebook\util\filesystem.pyc", line 318, in open_url
WindowsError: [Error 3] Das System kann den angegebenen Pfad nicht 
finden: u'file:///mailto:<email address hidden>'
2012-01-26 11:57:10,858 INFO     Trying to open 
file:///mailto:<email address hidden> with webbrowser


-------- Original-Nachricht --------
Betreff: Re: [Bug 921593] [NEW] link to 'thunderlink://xxxx ' fails on 
windows
Von: Jendrik Seipp <email address hidden>
An: <email address hidden>
Datum: 25.01.2012 15:57

> Thanks for the report. I have never seen "thunderlink" before. You can
> add normal mails by using
>
> [myLink  ""mailto:<email address hidden>""]
>
> Does it work under windows?
>
> Alternatively you can export your content and see if opening the links
> in a browser works. Does it?
>

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-01-26T11:30:25Z):

----------------------------------------

You're right. That is a bug :)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-02-24T18:46:17Z):

----------------------------------------

I fixed this bug in trunk and compiled a beta version: http://dl.dropbox.com/u/4780737/rednotebook-1.4.0-beta2.exe

Can you confirm that this fixes the error and doesn't break the other links or image embedding, please?

**Comment by jendrikseipp** [comment]
*Original comment by* **bau-x** (2012-02-28T11:33:12Z):

----------------------------------------

I tested and everything works fine now, thanks!


-------- Original-Nachricht --------
Betreff: [Bug 921593] Re: link to 'thunderlink://xxxx ' fails on windows
Von: Jendrik Seipp <email address hidden>
An: <email address hidden>
Datum: 24.02.2012 19:46

> I fixed this bug in trunk and compiled a beta version:
> http://dl.dropbox.com/u/4780737/rednotebook-1.4.0-beta2.exe
>
> Can you confirm that this fixes the error and doesn't break the other
> links or image embedding, please?
>
> ** Changed in: rednotebook
>         Status: Confirmed =>  Triaged
>
> ** Changed in: rednotebook
>         Status: Triaged =>  Fix Released
>
> ** Changed in: rednotebook
>         Status: Fix Released =>  Fix Committed
>

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-02-28T11:48:40Z):

----------------------------------------

Thanks for testing this.
