### ISSUE TITLE
cloud words and preview mode cannot be seen

### ISSUE THREAD

**Issue by LeoDariox** [jendrikseipp/rednotebook#755]
**The cloud words and preview mode cannot be seen**

in RedNotebook version 2.31, Manjaro Gnu/Linux (using dark theme) 
![Screenshot_20240308_200112](https://github.com/jendrikseipp/rednotebook/assets/88386243/7278bb3e-4f51-4b56-8f1e-476511d3b156)

**Comment by jendrikseipp** [comment]
Thanks for the report! Could you please start RedNotebook from the terminal and paste the output here?

**Comment by LeoDariox** [comment]
Of course!
`INFO     Using GtkSourceView 4
Adding /usr/lib/python3.11/site-packages to sys.path
INFO     Available versions of the WebKit2 namespace: ['4.0', '4.1']
INFO     Loaded version of the WebKit2 namespace: 4.1
INFO     Locale path: /usr/share/locale
2024-03-11 15:12:42,142 INFO     Writing log to file "/home/leo/.rednotebook/rednotebook.log"
2024-03-11 15:12:42,142 INFO     System encoding: utf-8
2024-03-11 15:12:42,142 INFO     Language code: es_AR

(rednotebook:83446): libenchant-WARNING **: 15:12:42.157: Error loading plugin: libhspell.so.0: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio


(rednotebook:83446): libenchant-WARNING **: 15:12:42.158: Error loading plugin: libnuspell.so.5: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio


(rednotebook:83446): libenchant-WARNING **: 15:12:42.158: Error loading plugin: libvoikko.so.1: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio


(rednotebook:83446): libenchant-WARNING **: 15:12:42.158: Error loading plugin: libaspell.so.15: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio

2024-03-11 15:12:42,159 INFO     Spell checking languages: ['en_US', 'en_US-large', 'es_AR']
2024-03-11 15:12:42,159 INFO     Spell checking dictionaries: [('en_US', <Enchant: Hunspell Provider>), ('en_US-large', <Enchant: Hunspell Provider>), ('es_AR', <Enchant: Hunspell Provider>)]
2024-03-11 15:12:42,301 INFO     Using LibYAML
2024-03-11 15:12:42,302 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2024-03-11 15:12:42,305 INFO     Peak memory: 118200204 KiB
`

**Comment by stevet11** [comment]
I had the same issue, here's the startup output:
```
INFO     Using GtkSourceView 4
Adding /usr/share/rednotebook to sys.path
INFO     Available versions of the WebKit2 namespace: ['4.0']
WARNING  WebKit2 4.1 not found. Trying to use arbitrary version. Error message: 'Namespace WebKit2 not available for version 4.1'
INFO     Loaded version of the WebKit2 namespace: 4.0
INFO     Locale path: /usr/share/locale
2024-04-02 01:16:11,692 INFO     Writing log to file "/home/thor/.rednotebook/rednotebook.log"
2024-04-02 01:16:11,692 INFO     System encoding: utf-8
2024-04-02 01:16:11,692 INFO     Language code: en_US
2024-04-02 01:16:11,706 INFO     Spell checking languages: ['en', 'en_AU', 'en_CA', 'en_GB', 'en_US', 'en_ZA']
2024-04-02 01:16:11,707 INFO     Spell checking dictionaries: [('en', <Enchant: Aspell Provider>), ('en_AU', <Enchant: Aspell Provider>), ('en_CA', <Enchant: Aspell Provider>), ('en_GB', <Enchant: Aspell Provider>), ('en_US', <Enchant: Aspell Provider>), ('en_ZA', <Enchant: Hunspell Provider>)]
2024-04-02 01:16:11,842 INFO     Using LibYAML
2024-04-02 01:16:11,844 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2024-04-02 01:16:11,846 INFO     Running in portable mode: False
2024-04-02 01:16:11,846 INFO     First Start: False
2024-04-02 01:16:11,846 INFO     RedNotebook version: 2.32
2024-04-02 01:16:11,848 INFO     System info: machine: x86_64, platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.35, processor: x86_64, python_version: 3.10.12, release: 6.5.0-26-generic, system: Linux, GTK: (3, 24, 33), Glib: (2, 71, 3), PyGObject: (3, 42, 1), YAML: 5.4.1, WebKit2: (2, 42, 5)
2024-04-02 01:16:12,095 DEBUG    Default font: Sans 10
2024-04-02 01:16:12,096 DEBUG    Default size: 10.0
2024-04-02 01:16:12,371 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2024-04-02 01:16:12,372 INFO     Cloud include list: ['mtv', 'spam', 'work', 'job', 'play']
2024-04-02 01:16:12,372 DEBUG    Start compiling regexes
2024-04-02 01:16:12,372 DEBUG    Finished
2024-04-02 01:16:12,400 DEBUG    Tray icon visible: False
2024-04-02 01:16:12,401 INFO     Opening journal at '/home/thor/Documents/Journal'
2024-04-02 01:16:12,402 DEBUG    Starting to load files in dir "/home/thor/Documents/Journal"
2024-04-02 01:16:12,402 DEBUG    Loading file "/home/thor/Documents/Journal/2023-06.txt"
2024-04-02 01:16:12,403 DEBUG    Loading file "/home/thor/Documents/Journal/2023-07.txt"
2024-04-02 01:16:12,403 DEBUG    Loading file "/home/thor/Documents/Journal/2024-03.txt"
2024-04-02 01:16:12,403 DEBUG    Loading file "/home/thor/Documents/Journal/2024-04.txt"
2024-04-02 01:16:12,403 DEBUG    Finished loading files in dir "/home/thor/Documents/Journal"
2024-04-02 01:16:12,569 DEBUG    Update the cloud
2024-04-02 01:16:12,574 DEBUG    Background color: rgb(252,252,252)
2024-04-02 01:16:12,574 DEBUG    Foreground color: rgb(33,33,33)
2024-04-02 01:16:12,576 DEBUG    Cloud updated
2024-04-02 01:16:12,579 INFO     Last backup was made 6 days ago
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 263x392: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 263x392: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 263x392: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
2024-04-02 01:16:15,167 DEBUG    Background color: rgb(252,252,252)
2024-04-02 01:16:15,167 DEBUG    Foreground color: rgb(33,33,33)
2024-04-02 01:16:15,167 DEBUG    Add mathjax code: False
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 760x578: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 760x578: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 760x578: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
2024-04-02 01:16:19,133 DEBUG    Main frame destroyed
2024-04-02 01:16:19,136 INFO     Nothing to save
2024-04-02 01:16:19,136 INFO     Goodbye!
2024-04-02 01:16:19,162 INFO     Peak memory: 134606024 KiB
```

I found that using:
`env WEBKIT_DISABLE_COMPOSITING_MODE=1 rednotebook`
seems to work around the issue, and I'm able to see previews again.

**Comment by LeoDariox** [comment]
@stevet11 
where should this command be entered?

**Comment by jendrikseipp** [comment]
@LeoDariox You can paste this command into a terminal window (Applications->Terminal).

@stevet11 Are you using the deb package or the flatpak version? Are you using Wayland?

**Comment by stevet11** [comment]
I'm using the Ubuntu PPA deb package.  I'm using x11.

**Comment by LeoDariox** [comment]
Thanks! work fine now!

**Comment by Nick222** [comment]
I see the same
Xubuntu 24.04
Rednotebook 2.33 deb from PPA

"env WEBKIT_DISABLE_COMPOSITING_MODE=1 rednotebook" work OK

**Comment by verify0097** [comment]
I installed the 2.7 beta release for Windows (rednotebook-2.7-rbabc69e.exe). After it installs I get an error when it tries to start.
![rednotebook-error](https://github.com/user-attachments/assets/1c3070db-7e57-4cb9-b12b-c118fcc5f680)

The rednotebook.log follows...

2024-10-10 15:39:10,909 INFO     Writing log to file "C:\Users\apswa\.rednotebook\rednotebook.log"
2024-10-10 15:39:10,909 INFO     System encoding: mbcs
2024-10-10 15:39:10,909 INFO     Language code: en_US
2024-10-10 15:39:10,940 INFO     Using pyyaml for loading and dumping
Traceback (most recent call last):
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 168, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\gui\main_window.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\gui\options.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\gui\editor.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\external\spellcheck.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python34\lib\site-packages\enchant\__init__.py", line 92, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python34\lib\site-packages\enchant\_enchant.py", line 102, in <module>
OSError: [WinError 193] <no description>

**Comment by verify0097** [comment]
> Version 2.7 is really old. I suggest you try a newer release.

Yikes! It sure is. Sorry about that. I was misreading the version numbers and not paying attention to the dates of posts. 

Thanks for the great work.
