### ISSUE TITLE
locale.strxfrm throws error 22 when passed category is not 

### ISSUE THREAD

**Issue by oussjarrousse** [jendrikseipp/rednotebook#777]
I am now getting an error related to the use of `locale.strxfrm` in 516 in `journal.py`.

```
Traceback (most recent call last):
  File "/Users/ouss/Documents/workspace/rednotebook/rednotebook/journal.py", line 624, in <module>
    main()
  File "/Users/ouss/Documents/workspace/rednotebook/rednotebook/journal.py", line 606, in main
    journal = Journal()
  File "/Users/ouss/Documents/workspace/rednotebook/rednotebook/journal.py", line 238, in __init__
    self.open_journal(journal_path)
  File "/Users/ouss/Documents/workspace/rednotebook/rednotebook/journal.py", line 401, in open_journal
    self.frame.categories_tree_view.categories = self.categories
  File "/Users/ouss/Documents/workspace/rednotebook/rednotebook/journal.py", line 514, in categories
    return sorted(
OSError: [Errno 22] Invalid argument
```

This happens when the `category` is in the `en_US.UTF-8` locale... for example Arabic characters...

**Comment by oussjarrousse** [comment]
duplicate of #778
