### ISSUE TITLE
Can't get past 'no such file' on MAC

### ISSUE THREAD

**Issue by DazMazz** [jendrikseipp/rednotebook#785]
Moved from Ubuntu to Mac 
I have reams of work history  but i cant get past this error...

** (process:37370): WARNING **: 14:13:18.623: Failed to load shared library '/private/tmp/glib-20241113-71834-rcv893/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' referenced by the typelib: dlopen(/private/tmp/glib-20241113-71834-rcv893/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib, 0x0009): tried: '/private/tmp/glib-20241113-71834-rcv893/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/glib-20241113-71834-rcv893/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file), '/private/tmp/glib-20241113-71834-rcv893/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file)
Traceback (most recent call last):
  File "/Users/me/Downloads/rednotebook-2.24/rednotebook/journal.py", line 105, in <module>
    from rednotebook.util import utils
  File "/Users/me/Downloads/rednotebook-2.24/rednotebook/util/utils.py", line 29, in <module>
    from gi.repository import GObject, Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/gi/importer.py", line 146, in create_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/gi/importer.py", line 147, in create_module
    dynamic_module = load_overrides(introspection_module)
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/gi/overrides/GLib.py", line 500, in <module>
    MainLoop = override(MainLoop)
  File "/Users/me/Library/Python/3.9/lib/python/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

**Comment by jendrikseipp** [comment]
Support for macOS is spotty at best, sorry. And I have no way of testing or debugging it. If you find a solution, I'd be happy to review a pull request.

**Comment by DazMazz** [comment]
Could you even suggest what dependency i might be missing based on the stack trace?

**Comment by jendrikseipp** [comment]
Maybe this helps? https://www.phind.com/search?cache=nvk8nfqfc42dtclzzast6wf4

**Comment by DazMazz** [comment]
What do you make of this error?

Adding /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages to sys.path
2024-11-15 19:59:57,710 INFO     Writing log to file "/Users/me/.rednotebook/rednotebook.log"
2024-11-15 19:59:57,710 INFO     System encoding: utf-8
2024-11-15 19:59:57,710 INFO     Language code: en_GB
Traceback (most recent call last):
  File "/opt/local/bin/rednotebook", line 6, in <module>
    import journal
ModuleNotFoundError: No module named 'journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/bin/rednotebook", line 12, in <module>
    import rednotebook.journal
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rednotebook/journal.py", line 177, in <module>
    from rednotebook.gui.main_window import MainWindow
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rednotebook/gui/main_window.py", line 28, in <module>
    from rednotebook.gui.options import OptionsManager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rednotebook/gui/options.py", line 27, in <module>
    from rednotebook.gui import editor
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rednotebook/gui/editor.py", line 35, in <module>
    DEFAULT_FONT = Gtk.Settings.get_default().get_property("gtk-font-name")
AttributeError: 'NoneType' object has no attribute 'get_property'

**Comment by jendrikseipp** [comment]
That error (Gtk.Settings.get_default() returning None) is most commonly seen when there's no screen, i.e., in a headless environment such as a remote server.
