### ISSUE TITLE
RedNotebook will not start

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#79]
Tried starting but it gets so far then shuts down.

Rednotebook version 1.5.0
Running Ubuntu 12.04

 I've tried starting in terminal and get the following
michael@michael-Dimension-4700:~$ rednotebook
INFO     Writing log to file "/home/michael/.rednotebook/rednotebook.log"
INFO     MathJax location: http://cdn.mathjax.org/mathjax/latest/MathJax.js
INFO     Running in portable mode: False
INFO     First Start: False
INFO     RedNotebook version: 1.5.0
INFO     System info: machine: i686, platform: Linux-3.2.0-32-generic-i686-with-Ubuntu-12.04-precise, processor: i686, python_version: 2.7.3, release: 3.2.0-32-generic, system: Linux, GTK version: (2, 24, 10), PyGTK version: (2, 24, 0), Yaml version: 3.10
INFO     Cloud ignore list: [u'comma', u'filter', u'separated', u'these', u'words']
INFO     Cloud include list: [u'job', u'mtv', u'play', u'spam', u'work']
INFO     Using zeitgeist: False
INFO     Opening journal at u'/home/michael/.rednotebook/data'
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    rednotebook.journal.main()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 602, in main
    journal = Journal()
  File "/usr/share/rednotebook/rednotebook/journal.py", line 251, in __init__
    utils.check_new_version(self, info.version, startup=True)
  File "/usr/share/rednotebook/rednotebook/util/utils.py", line 109, in check_new_version
    new_version = get_new_version_number()
  File "/usr/share/rednotebook/rednotebook/util/utils.py", line 97, in get_new_version_number
    project_xml = urlopen('http://rednotebook.sourceforge.net/index.html').read()
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

 I have used RedNotebook for some time and this problem has only happened recently.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-10-24T08:19:41Z):

----------------------------------------

This problem was probably due to a server outage at sourceforge. It 
should be fixed by now, but I'll also have to adapt the code for such 
failures. Thanks for your report!
