### ISSUE TITLE
RedNotebook fails to start

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#80]
RedNotebook produces an error on startup (Win7-32).
The content of <Rednotebook.exe.log> is:

Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 60, in <module>
  File "rednotebook\util\filesystem.pyc", line 37, in get_utf8_path
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 10: invalid start byte
Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 60, in <module>
  File "rednotebook\util\filesystem.pyc", line 37, in get_utf8_path
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 10: invalid start byte

Thanks for informations on that.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-11-01T18:25:23Z):

----------------------------------------

I assume you're using RedNotebook 1.5, the installed version (not the PortableApps one)? 

Can you please provide the full path to the rednotebook.exe file (Maybe do a search for it)?

**Comment by jendrikseipp** [comment]
*Original comment by* **abindietonne** (2012-11-15T22:06:43Z):

----------------------------------------

It is the 1.5.0 portable version. But I have good news: I moved the RedNotebook folder from the desktop to a more "regular" folder (c:\temp) and it works.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-11-15T22:18:10Z):

----------------------------------------

What is the full path to the desktop? 

Can you check if the error still happens with version 1.6.1, please? If it does, it might affect many users with non-ASCII paths.

**Comment by jendrikseipp** [comment]
*Original comment by* **abindietonne** (2012-11-17T22:31:26Z):

----------------------------------------

Hi Jendrik,

here are the infos:

Path of the portable 1.5 EXE:  <C:\Users\Jörg\Desktop\RedNotebookPortable>

I have also installed the 1.6.1 - twice:
1) in <C:\Program Files\RedNotebook>. Everything runs fine
2) in <C:\Program Files\Jörg>. RedNotebook failed to start and wasn't able to write the logfile also (see attachment).
But I think that is a credential problem, because the user "Jörg" is restricted and has not enough rights to write into the Program files folder.

I hope that helps.
Jörg (from Germany)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-11-17T23:09:43Z):

----------------------------------------

Thanks for the info. I think the program fails to start because of the ö 
in your name. Could you please try putting version 1.6.1 to 
C:\Users\Jörg\Desktop\RedNotebookPortable1.6.1 and see if it fails as 
well and with the same error message?

**Comment by jendrikseipp** [comment]
*Original comment by* **abindietonne** (2012-11-20T22:54:34Z):

----------------------------------------

Launching the 1.6.1 portable in <C:\Users\Jörg\Desktop\RedNotebookPortable> fails with the following error:

Traceback (most recent call last):
  File "rednotebook", line 11, in <module>
  File "rednotebook\journal.pyc", line 57, in <module>
  File "rednotebook\util\filesystem.pyc", line 37, in get_utf8_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 10: ordinal not in range(128)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-11-20T23:04:30Z):

----------------------------------------

Thanks, it seems RedNotebook 1.6.1 stilldoesn't like Umlauts... I'll 
look into it.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-26T01:26:21Z):

----------------------------------------

The new beta https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta1.exe should fix that problem. Can you confirm that?

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-26T14:31:01Z):

----------------------------------------

This newer beta fixes a svg problem: https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta2.exe

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-01-22T00:08:56Z):

----------------------------------------

This has been fixed in version 1.6.6.
