### ISSUE TITLE
Help about  does not show anything

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#81]
While packaging and testing the latest 1.6.1  build for Portableapps noted that clicking help and about does not show anything not even version number, checked local install and same results.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-11-12T09:09:43Z):

----------------------------------------

Do you get any error messages in the log?

**Comment by jendrikseipp** [comment]
*Original comment by* **rubinstein** (2012-11-12T12:05:26Z):

----------------------------------------

I have the same problem, with version 1.6.1 under Windows 7.

Here is the error message from the log:

Traceback (most recent call last):
  File "rednotebook\gui\menu.pyc", line 291, in on_info_activate
glib.GError: Bildlader-Modul konnte nicht geladen werden: C:/Python27/Lib/site-packages/gtk-2.0/runtime/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll: `C:/Python27/Lib/site-packages/gtk-2.0/runtime/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll': Das angegebene Modul wurde nicht gefunden.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-11-12T13:12:44Z):

----------------------------------------

Thanks for the log, it helped a lot to fix the issue. Version 1.6.2 will 
include the fix.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-26T00:43:04Z):

----------------------------------------

This should be fixed in https://www.dropbox.com/sh/bpghpwx7r5ee7v1/wMSMY_hcnu/rednotebook-1.6.5-beta1.exe 
Can you confirm that?

**Comment by jendrikseipp** [comment]
*Original comment by* **vf2nsr** (2012-12-26T02:01:37Z):

----------------------------------------

I can neither confirm nor not confirm at this point.  I am currently on Windows
8 and have installed the file and mow Rednotebook will not even launch for
me.  I have even forced run as admin  and still will not launch


LOG FILE

2012-12-25 20:57:45,851 DEBUG    sys.stdout logging level: 20
2012-12-25 20:57:45,851 INFO     Writing log to file
"C:\Users\Patrick\.rednotebook\rednotebook.log"
2012-12-25 20:57:45,867 INFO     MathJax location:
http://cdn.mathjax.org/mathjax/latest/MathJax.js
2012-12-25 20:57:46,476 INFO     Running in portable mode: False
2012-12-25 20:57:46,476 INFO     First Start: True
2012-12-25 20:57:46,476 INFO     RedNotebook version: 1.6.5
2012-12-25 20:57:46,476 INFO     System info: machine: AMD64, platform:
Windows-post2008Server-6.2.9200, processor: Intel64 Family 6 Model 42
Stepping 7, GenuineIntel, python_version: 2.7.3, release: post2008Server,
system: Windows, GTK version: (2, 24, 10), PyGTK version: (2, 24, 0), Yaml
version: 3.10
Traceback (most recent call last):
  File "rednotebook", line 12, in <module>
  File "rednotebook\journal.pyc", line 595, in main
  File "rednotebook\journal.pyc", line 243, in __init__
  File "rednotebook\gui\main_window.pyc", line 80, in __init__
glib.GError: Unable to load image-loading module:
C:/Python27/Lib/site-packages/gtk-2.0/runtime/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll:
`C:/Python27/Lib/site-packages/gtk-2.0/runtime/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.dll':
The specified module could not be found.



Patrick

*<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><
*
*The individual has always had to struggle to keep from being overwhelmed
by the tribe.
If you try it, you will be lonely often, and sometimes frightened.
But no price is too high to pay for the privilege of owning yourself.
- Friedrich
Nietzsche**

 <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><*

*Developer for  PortableApps.com <http://portableapps.com/>  My Current
list of Apps <http://portableapps.com/node/30620> are located on the page.*

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-26T10:43:05Z):

----------------------------------------

Thanks for the info. I will fix this and send you a new beta soon.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-26T14:31:25Z):

----------------------------------------

This newer beta fixes a svg problem: https://dl.dropbox.com/u/4780737/rednotebook-1.6.5-beta2.exe

**Comment by jendrikseipp** [comment]
*Original comment by* **vf2nsr** (2012-12-26T16:24:38Z):

----------------------------------------

*That one seemed to wrok much better.  Although I had to run as admin in
Windows 8

Thanks Patrick
*
*<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><
*
*The individual has always had to struggle to keep from being overwhelmed
by the tribe.
If you try it, you will be lonely often, and sometimes frightened.
But no price is too high to pay for the privilege of owning yourself.
- Friedrich
Nietzsche**

 <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><*

*Developer for  PortableApps.com <http://portableapps.com/>  My Current
list of Apps <http://portableapps.com/node/30620> are located on the page.*

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-27T10:52:29Z):

----------------------------------------

So the "about" dialog works?

Did you have to run the installer or the program as root?

**Comment by jendrikseipp** [comment]
*Original comment by* **vf2nsr** (2012-12-27T11:25:11Z):

----------------------------------------

The about dialog worked,  I Installed it root, I did not work on it ptrtable
yet as was not sure how cloe this was ready for release.  can check on it
later in the day if you like?

Patrick


*<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><
*
*The individual has always had to struggle to keep from being overwhelmed
by the tribe.
If you try it, you will be lonely often, and sometimes frightened.
But no price is too high to pay for the privilege of owning yourself.
- Friedrich
Nietzsche**

 <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><*

*Developer for  PortableApps.com <http://portableapps.com/>  My Current
list of Apps <http://portableapps.com/node/30620> are located on the page.*

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-27T11:32:12Z):

----------------------------------------

Thanks. I'll probably make a release soon, then you can package it for 
PortableApps.

**Comment by jendrikseipp** [comment]
*Original comment by* **vf2nsr** (2012-12-27T12:18:53Z):

----------------------------------------

Thanks I appreciate your hard work...many changes expected between the beta
I looked at and the final one?
*<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><
*
*The individual has always had to struggle to keep from being overwhelmed
by the tribe.
If you try it, you will be lonely often, and sometimes frightened.
But no price is too high to pay for the privilege of owning yourself.
- Friedrich
Nietzsche**

 <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><*

*Developer for  PortableApps.com <http://portableapps.com/>  My Current
list of Apps <http://portableapps.com/node/30620> are located on the page.*

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2012-12-27T12:26:29Z):

----------------------------------------

no, it'll be the same file :)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-01-21T17:37:19Z):

----------------------------------------

This has been fixed in 1.6.6.
