### ISSUE TITLE
txt2tags aborted by unknown error, fails to display notes

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#86]
Rather than display my notes for February 25, it shows this error:

Sorry! Txt2tags aborted by an unknown error. Please send the following Error Traceback to the author (<email address hidden>): Traceback (most recent call last): File "/usr/share/rednotebook/rednotebook/util/markup.py", line 374, in convert body, toc = txt2tags.convert(txt, config) File "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 5132, in convert ret.extend(BLOCK.blockout()) File "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3550, in blockout result = getattr(self, blockname)() File "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3799, in deflist def deflist(self): return self.list('deflist') File "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3854, in list z,term,rest = item[0].split(SEPARATOR, 2) ValueError: need more than 2 values to unpack

I refer here to the 'preview' mode and not to edit mode. If I copy and paste the contents to another day it results in the same error.

I have also e-mailed the address in the error message. Please let me know what more information I can provide.

**Comment by jendrikseipp** [comment]
*Original comment by* **sln45** (2013-02-27T05:41:30Z):

----------------------------------------

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-02-27T10:28:40Z):

----------------------------------------

Can you please send the day's text from edit mode as well?
Am 27.02.2013 06:50 schrieb "Mr. Spacklecrisp" <email address hidden>:

> Public bug reported:
>
> Rather than display my notes for February 25, it shows this error:
>
> Sorry! Txt2tags aborted by an unknown error. Please send the following
> Error Traceback to the author (<email address hidden>): Traceback (most
> recent call last): File
> "/usr/share/rednotebook/rednotebook/util/markup.py", line 374, in
> convert body, toc = txt2tags.convert(txt, config) File
> "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 5132, in
> convert ret.extend(BLOCK.blockout()) File
> "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3550, in
> blockout result = getattr(self, blockname)() File
> "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3799, in
> deflist def deflist(self): return self.list('deflist') File
> "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3854, in
> list z,term,rest = item[0].split(SEPARATOR, 2) ValueError: need more
> than 2 values to unpack
>
> I refer here to the 'preview' mode and not to edit mode. If I copy and
> paste the contents to another day it results in the same error.
>
> I have also e-mailed the address in the error message. Please let me
> know what more information I can provide.
>
> ** Affects: rednotebook
>      Importance: Undecided
>          Status: New
>
> --
> You received this bug notification because you are subscribed to
> RedNotebook.
> https://bugs.launchpad.net/bugs/1133945
>
> Title:
>   txt2tags aborted by unknown error, fails to display notes
>
> Status in RedNotebook - A Desktop Journal:
>   New
>
> Bug description:
>   Rather than display my notes for February 25, it shows this error:
>
>   Sorry! Txt2tags aborted by an unknown error. Please send the following
>   Error Traceback to the author (<email address hidden>): Traceback (most
>   recent call last): File
>   "/usr/share/rednotebook/rednotebook/util/markup.py", line 374, in
>   convert body, toc = txt2tags.convert(txt, config) File
>   "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 5132,
>   in convert ret.extend(BLOCK.blockout()) File
>   "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3550,
>   in blockout result = getattr(self, blockname)() File
>   "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3799,
>   in deflist def deflist(self): return self.list('deflist') File
>   "/usr/share/rednotebook/rednotebook/external/txt2tags.py", line 3854,
>   in list z,term,rest = item[0].split(SEPARATOR, 2) ValueError: need
>   more than 2 values to unpack
>
>   I refer here to the 'preview' mode and not to edit mode. If I copy and
>   paste the contents to another day it results in the same error.
>
>   I have also e-mailed the address in the error message. Please let me
>   know what more information I can provide.
>
> To manage notifications about this bug go to:
> https://bugs.launchpad.net/rednotebook/+bug/1133945/+subscriptions
>

**Comment by jendrikseipp** [comment]
*Original comment by* **thatscottishengineer** (2013-02-27T16:16:16Z):

----------------------------------------

Well it appears to be part of the Nelson Lichtenstein section that causes the problem. I haven't been able to trace it any further than that.

**Comment by jendrikseipp** [comment]
*Original comment by* **thatscottishengineer** (2013-02-27T16:19:50Z):

----------------------------------------

As a quick fix, if you put a hyphen in the first line of that section, it seems to stop the crash however that doesn't fix the underling bug.

**Comment by jendrikseipp** [comment]
*Original comment by* **thatscottishengineer** (2013-02-27T18:23:07Z):

----------------------------------------

So after further investigation it seems to be caused by:

: line one
line two
 - line three
- line four

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-02-28T12:56:45Z):

----------------------------------------

I added a better error message if those errors occur and filed a bugreport for txt2tags: https://code.google.com/p/txt2tags/issues/detail?id=173. I think we cannot prevent invalid markup to be entered so I think showing an error message is better than trying to fix bugs that only occur for invalid markup.

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-03-01T19:18:20Z):

----------------------------------------

Fixed in 1.7.0
